### ISSUE TITLE
Add custom pagination [button like pagination filled by some text] 

### ISSUE THREAD

**Issue by walifaizy** [kidjp85/react-id-swiper#105]
I am trying to get some functionality where I can add custom tiles instead of pagination(Example slider is attached), I know there is an option of custom pagination but I am not able to add custom button tiles, I have to edit global scss file for that or it can not  be achieve

![screen shot 2017-11-16 at 2 59 35 pm](https://user-images.githubusercontent.com/17082693/32888032-6965bc68-cadf-11e7-9759-1a12eeaf0bb5.png)

**Comment by kidjp85** [comment]
Hi @walifaizy , you can use 2 slides to achieve this behavior. Please refer demo page for implementation method (Thumbs Gallery With Two-way Control)

**Comment by walifaizy** [comment]
thanks @kidjp85 , solved my issue
