### ISSUE TITLE
Mousewheel Scroll does not work if mousemouse event does not fire.

### ISSUE THREAD

**Issue by YashYash** [kidjp85/react-id-swiper#107]
When mousewheel is set to true, getting to slide 2 from slide 1 works fine. Once you get to slide 2, if you do not move your mouse, you will no longer be able to switch slides unless you move your mouse again.

**Comment by kidjp85** [comment]
Hi @YashYash , can u specify more detailed ? Like which browser did u use ? I tested on Chrome, I couldn't reproduce it
