### ISSUE TITLE
Need Help: Items shown vertically 

### ISSUE THREAD

**Issue by Altiano** [kidjp85/react-id-swiper#112]
Basically, this is my code: 
    
```
import Swiper from 'react-id-swiper';

render () {
  return (
      <Swiper >
          <div>1</div>
          <div>2</div>
          <div>3</div>
          <div>4</div>
       </Swiper>
  )
}
```

no CSS styling !

Screenshot:
![screenshot from 2017-11-22 17-43-41](https://user-images.githubusercontent.com/8316282/33120403-ed2b0b3a-cfac-11e7-9bdc-4aff1e13ca43.png)

**Comment by kidjp85** [comment]
@Altiano : You have to load styles file. Please check README

**Comment by Altiano** [comment]
@kidjp85 Yupp! Thanks!
