### ISSUE TITLE
Handling Swiper API events

### ISSUE THREAD

**Issue by Altiano** [kidjp85/react-id-swiper#113]
How to handle Swiper API events using the react component?

http://idangero.us/swiper/api/#events

**Comment by kidjp85** [comment]
@Altiano , you provide handling events in params like

```javascript
const params = {
     on: {
           'init': () => {}
           'slideChange': () => {}
     }
}
```

Swiper 4.x doesn't provide swiper instance in event handling callback anymore, so if you want to use swiper instance in callback function, you need to  get it from ref like example in README

**Comment by Altiano** [comment]
@kidjp85 Cool! Thanks!
