### ISSUE TITLE
Width of slides isn't set if the slide is React component

### ISSUE THREAD

**Issue by vitalybe** [kidjp85/react-id-swiper#116]
If I do a regular slide, per docs, everything works fine:

        <Swiper>
          <div className="slide">Awesome slide</div>
          <div className="slide">Awesome slide</div>
          <div className="slide">Awesome slide</div>
        </Swiper>

However, if I try to encapsulate the slide in a component, like so:

```
        function MyComponent(props) {
          return <div className="slide">Awesome slide</div>
        }
```
```
        <Swiper>
          <MyComponent/>
          <MyComponent/>
          <MyComponent/>
        </Swiper>
```

Then the whole Swiper gets broken - I see all slides at once. It seems to be happening because Swiper doesn't set the width of the div inside the components in this case.

The only solution I found is something like that:

        <Swiper>
          <div><MyComponent/></div>
          <div><MyComponent/></div>
          <div><MyComponent/></div>
        </Swiper>

I thought that perhaps `MyComponent` would be getting the `width` as a prop and I could propagate to its children. However, there is no such prop.

Since I assume the issue stems from the original, non-react, library, how about a fix that does the following:

* Goes over every provided child
* Wraps it in a div

**Source**
https://github.com/vitalybe/react-test/tree/react-id-swiper

**Screenshot of the issue** 

![image](https://user-images.githubusercontent.com/1933752/33426379-3be9d544-d5ca-11e7-9f8c-43fc6baaf92c.png)

**Comment by kidjp85** [comment]
Hi @vitalybe ,
I also faced this problem before. Still finding the way to solve. If u have any idea, pls let me know

**Comment by gareys** [comment]
Personally, I think the fix is to wrap your children in a <div> like you've done @vitalybe.
Digging deeper would be to investigate why [https://github.com/kidjp85/react-id-swiper/blob/fda12d3ccc0fd7f781a84d35bb1c917b03067d0a/src/index.js#L466](this line) doesn't just pass through any child component.

**Comment by vitalybe** [comment]
Yeah, I did it in a more generic way though eventually:

```
class FixedSwiper extends Component {
  render() {
    return (
      <Swiper>
        {this.props.children.map(child => {
          return <div>{child}</div>;
        })}
      </Swiper>
    );
  }
}
```

So I can use it like so:

        <FixedSwiper>
          <MyComponent />
          <MyComponent />
          <MyComponent />
        </FixedSwiper>

Source:
https://github.com/vitalybe/react-test/blob/2b0c45d08fa5579fdb0b6312fcfa7b518608b2b5/src/App.js

**Comment by kidjp85** [comment]
I tried this before too. But I didn't put in lib file, because I don't wanna to wrap children component in a specific wrapper like `div`

**Comment by dzek69** [comment]
Yeah, wrapping could cause more issues than it solve. Like making SEO issues worse and I'm trying to fix current SEO issues in this PR: https://github.com/kidjp85/react-id-swiper/pull/120

I do it like @vitalybe and it's working just fine. I'm rendering `div` in my component and wrapping them with `li`s when rendering Swiper children.
