### ISSUE TITLE
Can't set initialSlide for dynamic content

### ISSUE THREAD

**Issue by jamland** [kidjp85/react-id-swiper#118]
I've might missed something but whatever value I set for `initialSlide` on Swiper with dynamic content it always start with 0.

```
const params = {
      initialSlide: 2,
      direction: 'vertical',
      height: 300,
      threshold: 10,
      slidesPerView: 1,
      observer: true,
      shouldSwiperUpdate: true,
      keyboard: true,
    }
....

<Swiper
   {...params}
   ref={node => node ? this.swiper = node.swiper : null}
>
     {
       this.props.children
     }
</Swiper>
```

But it works well for static number of children 😐
What is wrong here?

**Comment by gareys** [comment]
I've always initialized the swiper with an `activeIndex` of whichever slide I wish to start on. I've always worked with a dynamic number of slides and this has worked for me.

**Comment by jamland** [comment]
Thanks @gareys! now it works better)

**Comment by Dhruval083** [comment]
@gareys can you please share code how you are initializing, I am not able to move the slider with `activeIndex`

**Comment by duwei54** [comment]
when set the slidesPerView: 'auto'   , the activeIndex is not work when init,  it always scroll to the last
`const params = {
  effect: 'coverflow',
  centeredSlides: true,
  watchSlidesVisibility:true,
  slidesPerView: 'auto',
  coverflowEffect: {
    rotate: 60,
    stretch: 30,
    depth: 150,
    modifier: 1,
    slideShadows: false
  }
};`
`let items = productList.map((slide, index) => {
  return (
    <div className={styles.card} key={slide.name + slide.price}>
      <img className={styles.productSwiper} alt={slide.name} src={slide.img}/>
      <span className={styles.price}>{slide.time + '分钟/' + slide.price}</span>
    </div>
  )
});`
`            <Swiper {...params} ref={self => swiperDom = self} initialSlide={1} activeIndex={1}>
              {items}
            </Swiper>`
