### ISSUE TITLE
noSwiping option fails when loaded first with false as option

### ISSUE THREAD

**Issue by stinaq** [kidjp85/react-id-swiper#121]
We use this library in our app, and it works really well, good work!
However, on one page we sometimes want to have the slider, sometimes not. When there is nothing to swipe between, we want the slider disabled. So we've used the `noSwiping` option, and it mostly works. But if the first data loaded has swipe and you then switch to having no swiping, you can still swipe.
I have set it up in a [codepen](https://codepen.io/stinaq/pen/MryJpW), and the same issue occurs there. If

``` 
 state = {
    shouldNotSwipe: false,
  }
```

is set from the beginning, you can't toggle it to not swipe. But if you change the code and
do

```
  state = {
    shouldNotSwipe: true,
  }
```

there is no problem toggling between the states.

This is the code we run in the app:

```
    const swipeOptions = {
      ...this.swiperParams,
      shouldSwiperUpdate: true,
      noSwiping: (!qppsImages.length),
    };
    const swipeItems = [viewportElement, ...qppsImages].map(SwipeItem);

    return (
      <Swiper {...swipeOptions} >
        {swipeItems}
      </Swiper>);
```

So if the `qppsImages` has no length at first load, it works fine when switching between modes, but if it has a length from the beginning swiping will still be enabled in the swiper.
I have also checked the actual values passed down to Swiper, and those are correct. `noSwiping` is set to true, but it still swipes.
In the React inspector, it looks like this: 
![image](https://user-images.githubusercontent.com/1426788/34160080-d5330e5e-e4cb-11e7-85eb-75b146fa2a91.png)

There are no pagination bullets, but it still swipes, though it of course doesn't switch slide, since there are no slides.
![dec-19-2017 14-54-50](https://user-images.githubusercontent.com/1426788/34160317-ad50d988-e4cc-11e7-9fa7-6b21ada3817f.gif)

Grateful for help!

**Comment by kidjp85** [comment]
Hi @stinaq , which version are you using now ? There was a bug related with no swiping , but it should be fixed in newest version

**Comment by stinaq** [comment]
I took the latest Swiper version in the Codepen, 4.0.6. And I copied the master branch of this repo to the Codepen, since I couldn't find a CDN of that :)
I also run the latest npm package in my app.

**Comment by kidjp85** [comment]
Make sure you did load stylesheet file. UMD build is now available, so u can try it on Codepen

**Comment by stinaq** [comment]
Did you look at the codepen I linked? I looks like it should, so I don't think the stylesheet is missing, it's just the swiping that doesn't work sometimes, depending on what is first set on `noSwiping`. And I don't know what UMD build is :)

**Comment by kidjp85** [comment]
Hi @stinaq , sorry for missing your codepen u linked.  If u wanna update params when `qppsImages ` is changed, u should use `rebuildOnUpdate = true`. It will delete old Swiper instance and replace new instance with updated params. Let me know if it is still not working for u

**Comment by stinaq** [comment]
We do that now, but it unfortunately has a huge performance impact. It just seems like a bug since it works differently depending on what the value on `noSwiping` is at load time.

**Comment by OrenSchwartz** [comment]
any news ? performance is awful when using noSwiping with revuildOnUpdate

**Comment by tomdracz** [comment]
Just encountered exactly the same bug.
If swiper initialised with `noSwiping: true` I can switch between false and true without issues later. However if `noSwiping: false` is set initially, updating it to true has no effect.

`rebuildOnUpdate` does kinda work but performance, look and feel do become horrible so not really a viable option
