### ISSUE TITLE
Lazy-load items/images in the carousel

### ISSUE THREAD

**Issue by iamsaksham** [kidjp85/react-id-swiper#124]
If the carousel is too long i.e 50 images in it, I wouldn't like to load all the images before hand. So i was looking for lazy loading the image.
Its stated in the docs, `http://idangero.us/swiper/api/#lazy` but the lazy load is not rendering images by using the stated steps. 
So how can I to achieve lazy load in the carousel? 
I checked out the code in the repo, it have param named `lazy` but the div structure and classes are not working as intended. Can I have an example how to add lazy-loading to the carousel

**Comment by Ixeso** [comment]
Did you find a way to lazy load images ?

**Comment by iamsaksham** [comment]
@Ixeso not yet. Even when I tried to add images later onClicks of previous and next, to the carousel then the swiper gets messed up with css.

**Comment by kidjp85** [comment]
Hi @iamsaksham ,

Please refer newest demo for 1.5.8, I added demo for lazyload image

**Comment by adFedorovich** [comment]
U```
 const params = {
    autoHeight: true,
    lazy: {
      loadPrevNext: true,
    },
  };
```
