### ISSUE TITLE
Cannot combine Carousel with Multi-Row

### ISSUE THREAD

**Issue by yvesbeutler** [kidjp85/react-id-swiper#125]
I'm not able to run the following configuration:

`const config = {
  slidesPerView: 'auto',
  slidesPerColumn: 2,
};`

There will be three columns instead of just two. If I define `slidesPerColumn: 4`, then it will display 3 columns. Is there any workaround to display exactly two columns, because `slidesPerColumn: 1` will just show one column.

Thanks in advance.

**Comment by kidjp85** [comment]
Hi @yvesbeutler 

When u have multi row per slide, u can't use `slidesPerView: 'auto'`. Please check Swiper Api for more detail.

> slidesPerView: 'auto' is currently not compatible with multirow mode, when slidesPerColumn > 1
