### ISSUE TITLE
notification when swiper object is created

### ISSUE THREAD

**Issue by jh3141** [kidjp85/react-id-swiper#126]
Using an older version of this component, I had a property `onInit` which allowed a callback to be initiated passing a copy of the `swiper` object immediately after it is created.  This facility seems to have disappeared with more recent versions.  Is there any chance of restoring it, as it provides the most convenient way of integrating directly to the underlying library?

**Comment by kidjp85** [comment]
Hi @jh3141 

From version 1.5.0, we use Swiper@4x, which has `swiper` instance removed from all callback function, like `onInit`. In order to use `swiper` instance, u can refer Readme. Thanks.
