### ISSUE TITLE
loadOnTransitionStart doesn't work

### ISSUE THREAD

**Issue by joe-f** [kidjp85/react-id-swiper#136]
`  const params = {
      pagination: {
        el: '.swiper-pagination',
        type: 'bullets',
        clickable: true,
        dynamicBullets: true
      },
      slidesPerView: 1,
      loop: true,
      preloadImages: false,
      lazy: {
        enabled: true,
        loadOnTransitionStart: true
      }
    };`

We need the image to start loading as soon as the swipe begins rather than waiting for the blur event. This property doesn't seem to be working however! Still only lazy loads on blur.

**Comment by joe-f** [comment]
@kidjp85 Any ideas on this issue?

**Comment by kidjp85** [comment]
Hi @joe-f , sorry for my late reply. It should not have `enabled` property in lazy params due to [API](http://idangero.us/swiper/api/#lazy). Only `lazy: { loadOnTransitionStart: true }` is enough

**Comment by joe-f** [comment]
Hey @kidjp85 thanks for the update!

I've tried this, and it does lazy load but it has the exact same effect as normal lazy loading. e.g. The image is loaded on release of the swipe

This should load the image as soon as the swipe begins, but it isn't.

**Comment by kidjp85** [comment]
Hi @joe-f , how do u check that it has the exact same effect as normal lazy loading ? Is it still showing loading spinner ? Cause when I tested in my local with demo page, I couldn't see loading spinner when I went to next slide.

**Comment by joe-f** [comment]
Hey @kidjp85,

No loading spinner, but this property should load the next image as soon as you start swiping, even before you release the swipe, but it isn't

Here is what is happening:
![2018-02-20 14 06 18](https://user-images.githubusercontent.com/1931624/36428437-c615f64a-1647-11e8-81d4-bc6fa400330a.gif)

**Comment by joe-f** [comment]
@kidjp85 Did you get a chance to look at the above animation, showing the problem?

**Comment by kidjp85** [comment]
Hi @joe-f , sorry for my late reply. I found one solution for u.

```javascript
{
    lazy: {
       loadPrevNext: true,
       loadPrevNextAmount: 1,  // number of slides u wanna preload on transition start
       loadOnTransitionStart: true
   }
}
```

**Comment by joe-f** [comment]
@kidjp85 Perfect that fixed it, thank you!

**Comment by AndreasCag** [comment]
Actually, it doesn't. @kidjp85 's solution just do this:
- when you start transition to next slide, swiper loads content on left and right sides of this slide, instead of loading content on left and right sides only if transition is ended.

But issue question relates to another possibility: lazy load slide image **only** when user tries to swipe to this slide.
