### ISSUE TITLE
Get slidePerView on Auto Slide

### ISSUE THREAD

**Issue by Ixeso** [kidjp85/react-id-swiper#137]
I'm using auto slide but I haven't found any way to get the number of slide on the view (without the name).
I needed to use slidesOffsetBefore and after to make some css tricks, but that way slider don't detect when there is not enough slides  and button next stay active. 
I would like to cancel slidesOffset when there is not enough slide to complete screen.
Do you think there is a way to do this or this could be a (graphic) enhancement ?

![image](https://user-images.githubusercontent.com/22478024/36024954-b2c256e2-0d91-11e8-8c09-e0bde41c224d.png)

**Comment by kidjp85** [comment]
If you set `slidePerView` with `auto`, I don't think you can get number of slide per one view.
