### ISSUE TITLE
Demo page broken in IE11

### ISSUE THREAD

**Issue by stinaq** [kidjp85/react-id-swiper#138]
This is what the demo page looks like in IE11 :(

![image](https://user-images.githubusercontent.com/1426788/36156597-d61d445a-10d7-11e8-9dbb-8f1c11f57b78.png)

The original Swiper seems to be running fine in IE11, and I know of one project using your react slider, where it works fine, so this seems more to be an issue on the demo page specifically

**Comment by kidjp85** [comment]
It looks like something wrong with polyfill for IE11. Thank you for your notice. I will fix it soon :)

**Comment by kidjp85** [comment]
@stinaq , it's fixed now
