### ISSUE TITLE
navigator is not defined

### ISSUE THREAD

**Issue by maheshambiga** [kidjp85/react-id-swiper#14]
I am trying to add this in an isomorphic app. When the server-side code is being run, app throws below error as navigator obj is undefined. 

node_modules\swiper\dist\js\swiper.js:3627
            var ua = navigator.userAgent.toLowerCase();
                     ^
ReferenceError: navigator is not defined.

Could you please help me on how to get rid of this issue.

**Comment by maheshambiga** [comment]
One solution I came up with is, requiring 'swiper' inside 'componentDidMount' as requiring at the top looking for navigator object immediately.

componentDidMount: function () {
            var Swiper = require('swiper');
            this.swiper = Swiper(ReactDOM.findDOMNode(this), objectAssign({}, this.props));
        }

**Comment by kidjp85** [comment]
@maheshambiga : Did u do server rendering or client ?

**Comment by maheshambiga** [comment]
initial set of html is created on server-side, later on event binding in done in client-side.

**Comment by kidjp85** [comment]
It should be fixed by idea from this https://github.com/nolimits4web/Swiper/issues/1541
