### ISSUE TITLE
freemode and slideperviews auto

### ISSUE THREAD

**Issue by quangtd101246** [kidjp85/react-id-swiper#144]
When I use option freemode and slideperviews 'auto', the container width be higher sum of all slide width. 
When I swipe to last slide, it do not stop swipe. How can I fix it?

**Comment by kidjp85** [comment]
Hi @quangtd101246 , when u use `{freeMode: true, slidesPerView: 'auto'}`, do u set specific width for each slide by stylesheet ? like `.swiper-slide { width: 25% }`
