### ISSUE TITLE
Could not find a declaration file for module 'react-id-swiper'

### ISSUE THREAD

**Issue by reZach** [kidjp85/react-id-swiper#148]
Hi,

I'm loading react-id-swiper like this, `import Swiper from 'react-id-swiper';` in my .tsx file, why am I getting this error?

My NPM is 5.8.0, and I installed the package with `npm install react-id-swiper`

**Comment by kidjp85** [comment]
Hi @reZach , sorry for my late response. I think the issue may come from `main` property from `package.json`. Currently I put it as `lib/index.js` , to fix this issue it should be `lib/index` only. I will change this in next version. For temporary solution you can import directly from src code `import Swiper from 'react-id-swiper/src`.

**Comment by reZach** [comment]
Hi @kidjp85 , thank you.

The following also does work until the next version comes out in case anyone was interested.
`var Swiper:any = require('react-id-swiper');`

**Comment by saintfirewater** [comment]
I added a new file, 'declarations.d.ts' in the root directory and a line of code in the file.
`declare module 'react-id-swiper';`

Then import statement worked well.

**Comment by saintfirewater** [comment]
@reZach I changed `main` property in `package.json`, then it worked well. May this causes another problem? Thanks.
