### ISSUE TITLE
Swiper skips a slide when roundLengths is true

### ISSUE THREAD

**Issue by myonov** [kidjp85/react-id-swiper#152]
Consider this example:
https://codepen.io/anon/pen/rdXdNb

When we swipe right to the end and then swipe left the second page is skipped and we reach the beginning. The problem persists only when `roundLengths` is `true` and there is only one slide at the last page.

Can you give us a hint what might be wrong?

**Comment by kidjp85** [comment]
Hi @myonov , I checked your example. That is really interesting bug. I am doing some research for this now, but I recommend u should also raise this issue to [Swiper](https://github.com/nolimits4web/swiper/issues).
