### ISSUE TITLE
Visibility classes aren't updated when moving to next slide

### ISSUE THREAD

**Issue by mirjacobsen** [kidjp85/react-id-swiper#159]
With watchSlidesVisibility & watchSlidesProgress enabled - on initial render, the visibility class (swiper-slide-visible) is added correctly (it is added to visible slides and not to hidden slides). 

However, when sliding to the next slide, the visibility class is added to the new slide, **but is not removed from the previous slide (which is now hidden from view)**. 

When then sliding to the previous slide, the visibility classes work as expected (gets removed from the now hidden next slide).

**Comment by kidjp85** [comment]
Hi @mirjacobsen , can u provide a demo by [Codesandbox](https://codesandbox.io/)?
