### ISSUE TITLE
Update of pagination

### ISSUE THREAD

**Issue by strarsis** [kidjp85/react-id-swiper#160]
Is it possible to update/notify the react swiper component when 
the DOM has changed and swiper slides have been added/removed?

Edit: The slider is indeed updated except the pagination.
This seems to be an issue with the underlying Swiper `update` method.

**Comment by zhuyali** [comment]
i have the same problem.

**Comment by zhuyali** [comment]
I think there is a solution to solve this problem.
https://github.com/kidjp85/react-id-swiper/blob/master/src/ReactIdSwiper.js#L404
in this if branch, append `this.swiper.pagination.render();`
@strarsis

**Comment by strarsis** [comment]
@zhuyali, @kidjp85: The link doesn't work anymore, has this been merged (and the branch removed)?

**Comment by kidjp85** [comment]
@strarsis u can try https://github.com/kidjp85/react-id-swiper/blob/master/src/index.js#L404
