### ISSUE TITLE
React Id Swiper breaks React Input component

### ISSUE THREAD

**Issue by hedikasmanto** [kidjp85/react-id-swiper#161]
Hi.

I have found some issue while implementing this great swiper with input from https://github.com/JedWatson/react-select and
https://jquense.github.io/react-widgets/api/DateTimePicker/

And here is "mini" script how to reproduce

Note : First Select can be selected, but while React Select wrapped with <Swapper>, react-select stop working

```
import React, { Component } from 'react'
import { NumberPicker, DateTimePicker } from 'react-widgets'
import Select from 'react-select'
import Swiper from 'react-id-swiper'

class Test extends React.Component {
  state = {
    selectedOption: ''
  }
  handleChange = selectedOption => {
    this.setState({ selectedOption })
    console.log(`Selected: ${selectedOption.label}`)
  }
  render() {
    const { selectedOption } = this.state
    return (
      <div>
        <Select
          name="form-field-name"
          value={selectedOption}
          onChange={this.handleChange}
          options={[{ value: 'one', label: 'One' }, { value: 'two', label: 'Two' }]}
        />
        <br /> <br />
        <br />
        <br />
        <br />
        <Swiper>
          <div>
            <Select
              name="form-field-name"
              value={selectedOption}
              onChange={this.handleChange}
              options={[{ value: 'one', label: 'One' }, { value: 'two', label: 'Two' }]}
            />
          </div>
          <div>
            <DateTimePicker />
          </div>
          <div>Slide 3</div>
          <div>Slide 4</div>
          <div>Slide 5</div>
        </Swiper>
      </div>
    )
  }
}

export default Test

```

**Comment by Praneeth-Pike** [comment]
@hedikasmanto  I'm having the same issue trying to use a component as a slide or inside a slide

**Comment by hedikasmanto** [comment]
Hi, @Praneeth-Pike 

I have created my own custom component using idangerous swiper but still no luck. I think this swiper only support div > image as child. So for workaround, I have replaced to another package. If you want, you can take a look. https://react-swipeable-views.com/demos/demos/ 

I hope that package can solve your problem.

**Comment by hedikasmanto** [comment]
@kidjp85 
I closed this issue.. If you want to investigate this issue.. please reopen

**Comment by BenjaOliva** [comment]
Same issue here, couldn't find any solution yet :(
