### ISSUE TITLE
Force ReRender When .map Completes

### ISSUE THREAD

**Issue by yuschick** [kidjp85/react-id-swiper#162]
Hello,

I am trying to use the swiper by populating it with a variable number of components based on an array. However, it seems the swiper needs to be rerendered after the `map` completes.

```
const colorParams = {
  slidesPerView: 3,
  spaceBetween: 30,
  freeMode: true,
  rebuildOnUpdate: true
};
```

```
<Swiper {...colorParams}>
  {
    ColorOptions.map((color) => {
      return (
        <ColorCircle /> /* puedo component code */
      );
   })
 }
</Swiper>
```

I don't see anything in the docs about this and am hoping I'm just missing something. All of my other testing looks to work fine up until I try to populate the slider with a `map` method.

**Comment by kidjp85** [comment]
Hi @yuschick , u can use params `rebuildOnUpdate: true` or `shouldSwiperUpdate : true`.  If u wanna rebuild Swiper each time component got re-rendered , just use `rebuildOnUpdate`. If u wanna update Swiper only, just use `shouldSwiperUpdate`

**Comment by omidnikrah** [comment]
I have the same issue and not working with `shouldSwiperUpdate ` and `rebuildOnUpdate `.

**Comment by malikgenius** [comment]
such a beautiful tool but doesnt work with map well, at tried above methods rebuildOnUpdate, at first run it doesnt work but if you navigate to any other page with router and come back it works, dont know how to fix it .. wish it worked well with fetched data from db via redux store .... 👎

**Comment by malikgenius** [comment]
worked like a charm i was using it in params but should be used like below 
 <Swiper {...params} shouldSwiperUpdate>

**Comment by kirsantov** [comment]
It's not working!

**Comment by configbug** [comment]
In your object ```colorParams``` include the following propertie

    rebuildOnUpdate: true

**Comment by osklars** [comment]
Neither props are recognized by react... 

React does not recognize the `rebuildOnUpdate` prop
React does not recognize the `shouldSwiperUpdate` prop

**Comment by CathyMacars** [comment]
I've tested them today and `rebuildOnUpdate` + `shouldSwiperUpdate` still don't work in react. We need something like this for some maps with more logic.

**Comment by Anonymous-dev-v** [comment]
> I've tested them today and `rebuildOnUpdate` + `shouldSwiperUpdate` still don't work in react. We need something like this for some maps with more logic.

hey, any updates ?
