### ISSUE TITLE
Swipe events

### ISSUE THREAD

**Issue by mbenjrinija** [kidjp85/react-id-swiper#167]
Hi, thank you very much for this contribution, i was unable to listen for events like 'on swipe' event.
 can anyone show me how to do so? i will be very thankful!!

**Comment by mbenjrinija** [comment]
It's ok guys i found it, 
`<Swiper
            {...mySwiper}
            index={HiddenMenuStore.slideIndex}
            onSwipe={this.didSwipe}
            ref={node => {
              if (node) this.swiper = node.swiper;
              this.swiper.on('slideChange', function () {
                console.log('slide changed');
              });
            }}
          >
            {renderedItems}
          </Swiper>`

**Comment by kidjp85** [comment]
Hi @mbenjrinija , u can add event from params like 

```javascript
params = {
    on: {
        'init': () => {}
        'slideChange': () => {......}
    }
}

```

More detail about event api is [here](http://idangero.us/swiper/api/#events)

**Comment by GaddMaster** [comment]
Hi

Why am I getting this error suddenly ....
index.js:1375 Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()

**Comment by ksy8230** [comment]
> Hi @mbenjrinija , u can add event from params like
> 
> ```js
> params = {
>     on: {
>         'init': () => {}
>         'slideChange': () => {......}
>     }
> }
> ```
> 
> More detail about event api is [here](http://idangero.us/swiper/api/#events)

thanks!!!
