### ISSUE TITLE
Yarn run : no dev server?

### ISSUE THREAD

**Issue by kimfucious** [kidjp85/react-id-swiper#169]
I've cloned this repo locally to check it out, because it looks **awesome**!

The docs say to run `yarn start` after running `yarn`.

Apparently, there is no start script in `package.json`, it looks like webpack-dev-server isn't a dependency.

Is there something obvious that I'm missing here?

**Comment by kidjp85** [comment]
Hi @kimfucious 

There is no demo in this repo anymore. You can checkout [this repo](https://github.com/kidjp85/react-id-swiper-demo.git
) for demo,  but it's out of date :). I will update with newest version when I have time.
