### ISSUE TITLE
image dont repeat in first load

### ISSUE THREAD

**Issue by jhserodio** [kidjp85/react-id-swiper#171]
Its dont repeat images in the first load.

```
let params = {
      pagination: {
        el: '.swiper-pagination',
        clickable: true,
        grabCursor: true,
        loop: true,
        centeredSlides: true,
        slidesPerView: 'auto',
    };
```
![screenshot-2018-6-9 copy of 3 4 rgln nvr](https://user-images.githubusercontent.com/10437390/41192551-e1643004-6bd5-11e8-88a5-cf8cb020407f.png)

**Comment by kidjp85** [comment]
Hi @jhserodio , can u provide a demo by [codepen](https://codepen.io/) or [codesandbox](https://codesandbox.io/)
