### ISSUE TITLE
Still need z-index of 1 on swiper-container and swiper-wrapper?

### ISSUE THREAD

**Issue by hedgerh** [kidjp85/react-id-swiper#179]
Currently using swiper, and we are having some z-index collisions with react-id-swiper, where our header menus are appearing behind the image swiper, instead of above them.  It's because our header is also using `z-index: 1`.  before we bump the z-index on our header, I wanted to ask if this z-index is still necessary in react-id-swiper.

Looking at the blame/comments, it was done 2 years ago to fix a flickering issue with Webkit:

https://github.com/kidjp85/react-id-swiper/blame/383baa7ffeffffe55d5609282f926ec323f4973d/src/styles/css/swiper.css#L18

**Comment by kidjp85** [comment]
Hi @hedgerh , I highly recommend you to use `Swiper`'s official stylesheet. From newest version `1.6.7`, I decided to drop supporting stylesheet within this library. Please try [newest stylesheet](https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.3.5/css/swiper.min.css) from Swiper team, and if you still have any issue, please re-open this ticket again. Thank you.

**Comment by fschoenfeldt** [comment]
I also have the feeling that the `z-index: 1` isn't needed anymore (v8.4.5)
