### ISSUE TITLE
Swiper dependency size is 174k

### ISSUE THREAD

**Issue by adardesign** [kidjp85/react-id-swiper#181]
The Swiper dependency when bundled for production via webpack is HUGE
it comes in as 174k

What can be done?
Can it be configured to only require the minimum dependencies?  

this is huge:
<img width="1869" alt="screen shot 2018-06-20 at 3 37 36 pm" src="https://user-images.githubusercontent.com/23543/41680617-1fc1df5e-74a0-11e8-9d7e-f805f8412d75.png">

**Comment by kidjp85** [comment]
Hi @adardesign , are you using `lightweight` version of  `react-id-swiper` already ? It can reduce around 40kb of minified size with less supported features.

**Comment by adardesign** [comment]
Thanks, 
Yea I have tried that, but the weight is still 134k which is bigger then react + redux together.
My question is if there is anything more that can be removed. (perhaps there is alot of old legacy browser support)

**Comment by kidjp85** [comment]
@adardesign , `Swiper` itself is pretty big due to large browsers and devices support.

**Comment by adardesign** [comment]
@kidjp85, Thanks, 
I added a comment on the forum 
http://idangero.us/swiper/forum/#!/general:bundlejs-925kb-with-webpac
I wish I can contribute to see where we can cut down.

Thanks again
