### ISSUE TITLE
Gallery with thumbnails

### ISSUE THREAD

**Issue by senorgeno** [kidjp85/react-id-swiper#182]
Hi there,

Is it possible to do something like this with react id swiper - https://github.com/nolimits4web/Swiper/blob/master/demos/300-thumbs-gallery.html

I need to get access to the swiper large galleries controller and add the thumbnails as the control 

I have something like this

```js
const largeGallery = {
...
};

const thumbnailGallery = {
...
};

largeGallery.controller.control = thumbnailGallery;
thumbnailGallery.controller.control = largeGallery;

```

But getting error that controller doesn't exist.

Can this be done?

**Comment by kidjp85** [comment]
Hi @senorgeno , you can refer example code for thumbnail gallery in demo page.
