### ISSUE TITLE
Getting console violation message

### ISSUE THREAD

**Issue by Dhruval083** [kidjp85/react-id-swiper#186]
I am getting below violation messsage in chrome console: 
`[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
attachEvents @ swiper.js:3107
init @ swiper.js:3838
Swiper @ swiper.js:3713
componentDidMount @ ReactIdSwiper.js:58
commitLifeCycles @ react-dom.development.js:8770
commitAllLifeCycles @ react-dom.development.js:9946
callCallback @ react-dom.development.js:542
invokeGuardedCallbackDev @ react-dom.development.js:581
invokeGuardedCallback @ react-dom.development.js:438
commitRoot @ react-dom.development.js:10050
performWorkOnRoot @ react-dom.development.js:11017
performWork @ react-dom.development.js:10967
requestWork @ react-dom.development.js:10878
scheduleWorkImpl @ react-dom.development.js:10732
scheduleWork @ react-dom.development.js:10689
scheduleTopLevelUpdate @ react-dom.development.js:11193
updateContainer @ react-dom.development.js:11231
(anonymous) @ react-dom.development.js:15226
unbatchedUpdates @ react-dom.development.js:11102
renderSubtreeIntoContainer @ react-dom.development.js:15225
render @ react-dom.development.js:15290
./src/index.js @ index.js:10
__webpack_require__ @ bootstrap cbfe2407f02a334dacd0:707
fn @ bootstrap cbfe2407f02a334dacd0:112
0 @ store.js:12
__webpack_require__ @ bootstrap cbfe2407f02a334dacd0:707
./node_modules/@firebase/app/dist/esm/index.js.Object.defineProperty.value @ bootstrap cbfe2407f02a334dacd0:805
(anonymous) @ bootstrap cbfe2407f02a334dacd0:805
Show 17 more blackboxed `

**Comment by kidjp85** [comment]
Hi @Dhruval083 , I don't think this is related to `react-id-swiper`. If you're still facing this issue , please open this ticket again.
