### ISSUE TITLE
about map

### ISSUE THREAD

**Issue by zhitongzhe** [kidjp85/react-id-swiper#188]
can I use map() to ergodic todos in swiper-slide？todos from asynchronous

**Comment by kidjp85** [comment]
Hi @zhitongzhe ,  sorry I can't get what you're trying to ask here, can u provide any demo code ?

**Comment by datnordstrom** [comment]
I think @zhitongzhe  is asking if you can loop through a list to dynamically create the slider.

**Comment by kidjp85** [comment]
@zhitongzhe , sorry for the late response. I think you can just wait until the asynchronous are loaded and then render the swiper. Like `asynchronousData ? <Swiper>....{asynchronousData.map(....)}</Swiper> ? null`
