### ISSUE TITLE
Is there a way of hiding custom arrows if not required?

### ISSUE THREAD

**Issue by apn2qq** [kidjp85/react-id-swiper#189]
Hi there, you have an excellent library. But I have a little problem:
I need to hide/disable custom arrows if not required, something like parameter watchOverflow for default arrows !?

**Comment by kidjp85** [comment]
Hi @apn2qq , if you don't provide `navigation` parameter, all navigator arrows should be hidden. Fix me if my understanding is not correct.

**Comment by Haraldson** [comment]
It would make sense if this was a ‘breakpoint-able’ setting, because I want the arrows on desktop, but don’t need them on mobile. This usecase doesn’t seem to work?
