### ISSUE TITLE
Typescript definitions files

### ISSUE THREAD

**Issue by Fenopiu** [kidjp85/react-id-swiper#190]
There will be soon Typescript definitions files?
Typescript is now very very very used as language so I don't think to be the only one who will be grateful for that ^_^

**Comment by kidjp85** [comment]
Hi @Fenopiu , for now we don't have any definition file. I am planning to implement in near future.

**Comment by devtobo** [comment]
Last version doesn't seem to have definition files still, why was this closed?

**Comment by PCASME** [comment]
+1 to have typescript definition files.

**Comment by pacurtin** [comment]
Did anybody ever create typescript definition files?

**Comment by 88mpg** [comment]
1.5 years later, please add definition files!

**Comment by sergiodevelops** [comment]
+1 to have typescript definition files.
