### ISSUE TITLE
Perform a slideTo

### ISSUE THREAD

**Issue by mrk197702** [kidjp85/react-id-swiper#197]
How can I perform a swiper's slideTo() when I click on a thumb?

**Comment by kidjp85** [comment]
Hi @mrk197702 ,  please refer demo from README to know how to create `swiper` instance

**Comment by mrk197702** [comment]
Hi @kidjp85 do you mean section "Example with manipulating swiper from outside swiper component" in readme? I got this error, I don't know how to fix it:
./src/components/SwiperComponent.jsx
Syntax error: C:/wamp64/www/marcocasarin_2017_react/src/components/SwiperComponent.jsx: Unexpected token (100:41)

   98 |     return(
   99 |       <div>
> 100 |         <Swiper {...params} ref={node => if(node) this.swiper = node.swiper }>
      |                                          ^
  101 |           <div>Slide 1</div>
  102 |           <div>Slide 2</div>
  103 |           <div>Slide 3</div>

**Comment by mrk197702** [comment]
the problem is ref

**Comment by kidjp85** [comment]
Can u provide a demo online ?

**Comment by kidjp85** [comment]
@mrk197702 , u can make ref to separated function like

```javascript
import React from 'react';
import Swiper from 'react-id-swiper';

export default class Example extends React.Component {
  constructor(props) {
    super(props);
    this.goNext = this.goNext.bind(this);
    this.goPrev = this.goPrev.bind(this);
    this.swiperRef = this.swiperRef.bind(this);
    this.swiper = null;
  }

  swiperRef(node) {
     if (node) {
         this.swiper = node.swiper
    }
  }

  goNext() {
    if (this.swiper) this.swiper.slideNext()
  }

  goPrev() {
    if (this.swiper) this.swiper.slidePrev()
  }

  render() {
    const params = {
      pagination: {
        el: '.swiper-pagination',
        type: 'bullets',
        clickable: true
      },
      navigation: {
        nextEl: '.swiper-button-next',
        prevEl: '.swiper-button-prev'
      }
    }

    return(
      <div>
        <Swiper {...params} ref={this.swiperRef}>
          <div>Slide 1</div>
          <div>Slide 2</div>
          <div>Slide 3</div>
          <div>Slide 4</div>
          <div>Slide 5</div>
        </Swiper>
        <button onClick={this.goNext}>Next</button>
        <button onClick={this.goPrev}>Prev</button>
      </div>
    )
  }
}
```

**Comment by mrk197702** [comment]
@kidjp85 it works thanks!

**Comment by intelligence** [comment]
Just want to say that I experienced issues with the demo code in the read me aswell, the example here however, works fine! :)
