### ISSUE TITLE
Use CDN

### ISSUE THREAD

**Issue by Zeindelf** [kidjp85/react-id-swiper#198]
Hi!

Is there a way to use Swiper CDN instead of self included?

Thanks.

**Comment by kidjp85** [comment]
Hi @Zeindelf , any reason for doing that?

**Comment by Zeindelf** [comment]
I do React components and hard coded HTML on my page, and both uses Swiper.

**Comment by kidjp85** [comment]
@Zeindelf , I see. I am thinking of removing `Swiper` from standalone build. But for now this is not supported.
