### ISSUE TITLE
Breaking change 1.6.6 -> 1.6.7 

### ISSUE THREAD

**Issue by frediana** [kidjp85/react-id-swiper#200]
Hello,

You introduced a breakign change (not packaging styles (less/sass/css) anymore.

In our poject we are importing those.

Can you fix and release a 1.6.8 that restore these styles?

Thanks!

**Comment by kidjp85** [comment]
Hi @frediana , as I mentioned in [this ticket](https://github.com/kidjp85/react-id-swiper/issues/195) , I will put style folder back but only support css.

**Comment by frediana** [comment]
Ok, css would be enough for me, thanks.
