### ISSUE TITLE
All items are showing on the first slide, and the others are empty

### ISSUE THREAD

**Issue by michaelluk** [kidjp85/react-id-swiper#201]
All items are showing on the first slide, and the other pages are empty. Am I missing something?

See the demo:
[![Edit react-id-swiper](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/j6oy1wnny)

Thanks.

**Comment by vasmotr** [comment]
same problem

**Comment by michaelluk** [comment]
@vasmotr Thanks. It's working now :)
