### ISSUE TITLE
Cant find SCSS file 

### ISSUE THREAD

**Issue by deependhamecha** [kidjp85/react-id-swiper#202]
I used 
```
import SwiperCSS from 'react-id-swiper/src/styles/scss/swiper.scss';
```

and cant find **Module react-id-swiper/src/styles/scss/swiper.scss**

Can any one please share how should I use scss file if its changed?

**Comment by kidjp85** [comment]
Hi @deependhamecha , it was removed from `1.6.7` , but I put it back from `1.6.8`
