### ISSUE TITLE
swipper not work correct on safari browser

### ISSUE THREAD

**Issue by dollar1610** [kidjp85/react-id-swiper#203]
Swiper - 1.6.1
Safari - 11.3
macOS - 10.13.6
react - 15.5.4
On Safari i have this 
[safari](https://i103.fastpic.ru/big/2018/0918/ae/_a0ab88da4a36d7018a9a1c76e4a598ae.png)
on chrome this 
[chrome](https://i101.fastpic.ru/big/2018/0918/7c/_ee549193eb1974e409c5ae7b65630f7c.png)
as you see, first 4 slides doesn't have style attribute which get 360px width and no have some classes, idk why. When i change width from 768, classes and style appears. And it's happens not always. 
code below in pic
[params](https://i101.fastpic.ru/big/2018/0918/34/33e4b5d675628517da70b96258476934.png)
[swiper](https://i99.fastpic.ru/big/2018/0918/88/6b643e697c3a6243d6f367ef2e066888.png)

**Comment by Dollar1610** [comment]
Any ideas? I'm didn't find any information about this problem. If you need more information please tell.

**Comment by kidjp85** [comment]
Hi @Dollar1610 , sorry for my late response. Please provide live demo from Copepen or Codesanbox.
Thank you
