### ISSUE TITLE
Slide Component requires incoming className prop

### ISSUE THREAD

**Issue by cloudratha** [kidjp85/react-id-swiper#205]
As the Swiper component clones the children and extends the `className` prop, I think it's important to detail in the Readme that your slide components should allow extending this prop.

**Comment by kidjp85** [comment]
Hi @cloudratha , thanks for the advice. I will try to update in next release

**Comment by guille-alibrate** [comment]
This is still missing in the docs. In the docs, there's no need for a class name. But without it, you can't navigate the slides (using the arrows).
