### ISSUE TITLE
Is it possible to start at а certain index on slider load

### ISSUE THREAD

**Issue by IvoRRaykov** [kidjp85/react-id-swiper#207]
Didn't find a functionality allowing me to select where should the slider start from. For example, if clickedIndex is 10, and show only 5 elements at once, i want to focus on my selected (unseeable) element. If really unexisting, guess this could be a nice addition to the slider :)

**Comment by mfundo** [comment]
@IvoRRyaykov I apolgise to mess your thread. I’m really stuck with getting an instance to my slider. Assuming you have yours running and you can call all swiper methods.

Do you mind sharing your way of the swiper setup?

**Comment by IvoRRaykov** [comment]
@mfundo here is my implementation of the slider. Call it by 
`<Slider className='someClass'>
       {this.getItems()}
  </Slider>`
[Slider.txt](https://github.com/kidjp85/react-id-swiper/files/2491177/Slider.txt)

**Comment by kidjp85** [comment]
Hi @IvoRRaykov , you can use params  { activeSlideKey: 'key name not index name' }.
