### ISSUE TITLE
Swiper is disappeared on browsers in iPhone (safari/chrome)  iOS 12

### ISSUE THREAD

**Issue by itays02** [kidjp85/react-id-swiper#211]
Hey, 
I've developed a component which uses your swiper-id and unfortunately,  the swiper is disappeared  on the browsers of Safari and Chrome in iPhone devices - only iOS 12+. Just when i'm clicking on it, the swiper is shown. 
You can see the problem when surfing this site through an iPhone device running ios 12.
**In order to see the swiper, you have to set the browser in "mobile mode" (in the developer tools).**

http://qmerce.github.io/static-testing-site/articles/strip_stage/

**Comment by chungwong** [comment]
1. please fix your link
2. As far as I can tell, I cannot see any swiper/slider on desktop Chrome

**Comment by itays02** [comment]
@chungwong I fixed it. Please notice again to try see this site in iPhone for example to see the error.

**Comment by kidjp85** [comment]
Hi @itays02 , sorry for late response . Did you test with newest version (1.6.9) ? I think this should relate to Swiper itself.
