### ISSUE TITLE
Fade effect isn't working on initial render

### ISSUE THREAD

**Issue by travishn** [kidjp85/react-id-swiper#219]
Currently using the below params for my swiper and whenever I click on one of the bullets to look at another div, it doesn't render anything new. I checked dev tools and the active class is being moved around correctly, so not too sure why nothing happens.

However, If I resize my browser and then click the bullets, it starts rendering properly all of a sudden. Currently using latest version of Chrome.

```javascript
  const params = {
    effect: 'fade',
    pagination: {
      el: '.swiper-pagination',
      clickable: true,
      bullets: true,
    },
  };
```

In addition, if I try to add in the fadeEffect object with the crossFade parameter and click the bullets, it just renders an empty div.

Update: Seems like the transition-durations are stuck at 300ms on the swipe-wrapper and swipe-slide classes after u click a bullet to change the slide the first time, causing the carousel to get stuck. Clicking the bullets afterwards only changes which slide is active and does not reset the stuck transition-duration UNLESS you resize your browser first for some reason.

Update 2: Hard refreshing also causes it to start working

**Comment by travishn** [comment]
In addition, if I try to add in the fadeEffect object with the crossFade parameter and click the bullets, it just renders an empty div

**Comment by seyyed-sina** [comment]
same issue here
