### ISSUE TITLE
weird slide click behaviour

### ISSUE THREAD

**Issue by b0gd4n** [kidjp85/react-id-swiper#220]
Hey there - been trying to find a light weight alternative to our current implementation of the slick carousel and found this one which seems to be perfect.
There is one issue however - there seems to be some weird behaviour when clicking the slides. For example, on pretty much all demos, after sliding once, if you click - just click (don't click & drag) the slide changes and it seems a bit erratic (either backwards or forwards).

**Comment by b0gd4n** [comment]
[here's](https://streamable.com/aizco) a screen recording of the issue. please note that I did NOT drag the slides in the recording, I just clicked a once in a part of the slide and then again immediately in another one. I believe it may have to do with how you're handling the drag event - I assume you are looking for mousedown vs mouseup coords. Is there a reason for not using something like HammerJS?

**Comment by Grosscorp** [comment]
The same problem, any ideas how to fix this?

**Comment by kidjp85** [comment]
You should confirm with Swiper team for more detail. From my opinion, I couldn't find any issue from your screen recording.
