### ISSUE TITLE
slideToClickedSlide property doesnt work

### ISSUE THREAD

**Issue by mfundo** [kidjp85/react-id-swiper#224]
I can't seem to get this work, please see setup below: All I need it getting the 'slideToClickedSlide' to work am I missing something?

`const params = {
     containerClass: 'number-slider__carousel',
     slideClass: 'number-slider__item',
     slideActiveClass: 'number-slider__item--active',
     slidePrevClass: 'number-slider__item--prev',
     slideNextClass: 'number-slider__item--next',
     slideToClickedSlide: true,
     preventClicks: false, //for testing purposes
     preventClicksPropagation: false, // for testing purposes
     centeredSlides: true,
     slidesPerView: 10,
     spaceBetween: 25,
      on: {
	 slideChange: () => {
	    this.swiper.name = this.props.name;
	    this.props.onChange(this.swiper);
	 },
	 init: () => {
	    this.onSliderInit()
	}
    }
}`

`<Swiper shouldSwiperUpdate
    {...params}
     ref={(el) => {
         if (el) {
	     this.swiper = el.swiper
	}
     }}>

      {this.props.items}

</Swiper>`

**Comment by mfundo** [comment]
@kidjp85 any ideas, really stuck. Thanks

**Comment by kidjp85** [comment]
Hi @mfundo , sorry for my late response. Can u provide a live demo from codesanbox ? Link is in Readme.
