### ISSUE TITLE
className properties should be additive

### ISSUE THREAD

**Issue by mschipperheyn** [kidjp85/react-id-swiper#225]
className specification should be additive not replace the classes.

I'm using css-modules and this replaces the actual className with a unique name to avoid collissions.

In Swiper if you add a `wrapperClass`, it fully replaces the existing classname. What it should do is add the class name. This way, you don't have to copy the entire class definition and potentially create an unseen bug bc you don't realize a different spec for a different screen size  or miss a sub selector (which are hard coded to the original classnames), and you can modify existing behaviour, instead of breaking it.

**Comment by kidjp85** [comment]
Hi @mschipperheyn , I will try to implement in next version. Really appreciate if you can make a PR

**Comment by Xapphire13** [comment]
@kidjp85, this issue is closed, but the problem still remains; can we re-open the issue?
