### ISSUE TITLE
swiper should be a peer dependency

### ISSUE THREAD

**Issue by mschipperheyn** [kidjp85/react-id-swiper#226]
swiper should be a peer dependency, not a direct dependency. This way, 0.0.x updates to swiper can be processed more easily

**Comment by kidjp85** [comment]
Hi @mschipperheyn , thank you for suggestion . But in my opinion, we still need to include Swiper for custom swiper version within the lib. That why I've put Swiper as peer dependency.

**Comment by kidjp85** [comment]
`Swiper` has become `peer-dependency` from v2.0.0
