### ISSUE TITLE
Center with centeredSlides option

### ISSUE THREAD

**Issue by qlerebours** [kidjp85/react-id-swiper#228]
Hello ! Thanks for the great work, this Swiper is very easy to use :+1: !

I just have one question concerning centering.
I use the swiper to display a list of pictures, but there are two cases:

- Case 1: Sometimes there are more pictures than the Swiper width (in this case, the swiper is usefull to see the hidden pictures)
- Case 2: Sometimes there are just a few pictures (less than the swiper width), in this case, the swiper is not very usefull, but this is dynamic, so i can't predict when there will be much pictures or not.

I think that the best behavior for centering would be:
- In the first case, it shouldnt be centered, because it would be wierd to start the pictures gallery by the middle picture. This weird behavior happens when I center with `centeredSlides` option.
- In the second case, it should be centered like we can do with a `display: flex` and `justify-content: center`.

First case with `centeredSlides={true}`
![image](https://user-images.githubusercontent.com/17043042/50557693-e3c79f80-0ce7-11e9-887f-9127ef5f716e.png)

First case with `centeredSlides={false}` but centered with `display: flex` and `justify-content: center` on the `Swipper` parent. As you can see, this is really centered, that's why we can't see the first picture (hidden on the left).
![image](https://user-images.githubusercontent.com/17043042/50557729-26897780-0ce8-11e9-98e1-46e40d113bc0.png)

To my mind, none of those solutions works, this is why i'd don't want the pictures to be centered in the first case:

First case with `centeredSlides={false}` NOT centered with flex. (**This is what i'd like to have**)
![image](https://user-images.githubusercontent.com/17043042/50557777-b4656280-0ce8-11e9-9025-99ddbe2091a6.png)

Second case with `centeredSlides={false}` but centered with `display: flex` and `justify-content: center` on the `Swipper` parent. (**This is what i'd like to have**)
![image](https://user-images.githubusercontent.com/17043042/50557764-9566d080-0ce8-11e9-98ad-84ad8d913408.png)

Second case without centering:
![image](https://user-images.githubusercontent.com/17043042/50557863-7157bf00-0ce9-11e9-88f6-a4bf8f3eeec7.png)

Do you know how I could center if there is a few pictures and not center if there are more pictures than swiper's width ?

**Comment by mingthegit** [comment]
@qlerebours  Can you try the following combination?

```
centeredSlides={false}
centerInsufficientSlides={true}
```

**Comment by qlerebours** [comment]
It works ! Thank you very much for the help

**Comment by lukecharle** [comment]
I'm experiencing a similiar issue. 

Tried using `true` for `centeredSlides` and then `false` for it along with `centerInsufficientSlides` as `true` but not having much luck.

```javascript
centeredSlides: true
```

<img width="1824" alt="Screenshot 2024-04-11 at 19 26 03" src="https://github.com/kidjp85/react-id-swiper/assets/115987937/f02cb692-e0d1-4e08-9114-a06c4b6e91c4">


```javascript
centeredSlides: false,
centerInsufficientSlides: true
```


<img width="1824" alt="Screenshot 2024-04-11 at 19 27 17" src="https://github.com/kidjp85/react-id-swiper/assets/115987937/fb2b8276-b235-4134-8ade-4b9885a56bed">


Ideally I would like the slides to be covering the entire width of the screen
