### ISSUE TITLE
direction: 'vertical' doesn't work, help!

### ISSUE THREAD

**Issue by ZouGuanghua** [kidjp85/react-id-swiper#229]
I use react-id-swiper in vertical direction, and it always in one screen.

```javascript
render() {

 const params = {

      direction: 'vertical',

      pagination: {

        el: '.swiper-pagination',

        clickable: true,

      }

  }

  return (
     <Swiper {...params}>
       <div>1</div>
       <div>2</div>
       <div>3</div>
       <div>4</div>
       <div>5</div>
    </Swpier>
  )
}
```

screenshot:

<br>

![image](https://user-images.githubusercontent.com/19298875/50871652-38a99b00-13f7-11e9-9fd9-b3b31fae0992.png)

I want every page is full screen, what should I do ?

**Comment by ZouGuanghua** [comment]
```
const params = {
     direction: 'vertical',
      speed: 600,
      height: window.innerHeight
}
```

it works

**Comment by deviant32** [comment]
Doesn't work for me, I get the same exact problem even with the solution.

**Comment by jeffceriello** [comment]
Same issue for me. Is there a solution to this?

**Comment by jeffceriello** [comment]
It seems to resolve to me when adding autoHeight: true
