### ISSUE TITLE
Swiper not working on Windows 10 touch screen

### ISSUE THREAD

**Issue by stinaq** [kidjp85/react-id-swiper#232]
When trying to swipe when being on a Windows touch screen, it isn't possible to swipe at all. The original http://idangero.us swiper works fine on the same computer.

**Comment by stinaq** [comment]
![img_7904](https://user-images.githubusercontent.com/1426788/51686521-cfc64380-1ff0-11e9-843b-0801565936fb.GIF)
Here is a gif of it working on the original swiper

**Comment by stinaq** [comment]
![animated](https://user-images.githubusercontent.com/1426788/51686598-f5534d00-1ff0-11e9-8454-c0a9d90db3d9.gif)
And here is me trying to do the exact same thing, on the same computer on the react id swiper

**Comment by joel1st** [comment]
https://github.com/kidjp85/react-id-swiper/issues/230

**Comment by kidjp85** [comment]
Released 1.6.9
