### ISSUE TITLE
Event onClick doesn't happen in chrome dev v73

### ISSUE THREAD

**Issue by MAKAPMOPKOBKUH** [kidjp85/react-id-swiper#233]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/22157309/51751965-0460fa80-20d8-11e9-888d-b3f51ef069ce.gif)

**Comment by Asp3ctus** [comment]
it's a bug of swiper itself
work around posted in https://github.com/nolimits4web/swiper/issues/2955
