### ISSUE TITLE
On dynamic slides must align slides with width if the number of slides is less then slidesperview ?

### ISSUE THREAD

**Issue by kishoreramkumar** [kidjp85/react-id-swiper#234]
I display slides depends on the data from backend. If i have only 2 slides but if the slidesperview is 4 it will show 2 slides and space for another 2 slides but I want the 2 slides to take the whole width

**Comment by kidjp85** [comment]
You should use params `rebuildOnUpdate` and updated your params each time when you receive data from server.

**Comment by brunomguimaraes** [comment]
Do you have an example? I can`t get it done
