### ISSUE TITLE
Custom transition effect as a parameter

### ISSUE THREAD

**Issue by ndotmdot** [kidjp85/react-id-swiper#237]
I would like to create a new transition effect which I can pass to the component as a parameter like so:

```
...

const params = {
  effect: 'newEffect',
  newEffectParams: {
    paramOne: 10,
  },
};

...

<Swiper {...params} />

...
```

I would like to code the effect in the same structure as it is done on the four build-in effects, for example, the "cover flow" /node_modules/swiper/src/components/effect-coverflow/effect-coverflow.js

Can someone help how (and where) to integrate a new effect in this manner of the four build-in ones?

Thanks a lot

**Comment by kidjp85** [comment]
I don't think `Swiper` itself is supporting this feature. For more info, you should ask Swiper team directly. Close this for now.
