### ISSUE TITLE
ReInit function not working when window resize

### ISSUE THREAD

**Issue by guideveloper** [kidjp85/react-id-swiper#239]
Hi So I have the carousel working in my react component but I want the Carousel Parameters to change if the use is on mobile or desktop.

I currently have this which works great if you load the carousel in the correct viewport...

`
const params = {
    centeredSlides: window.innerWidth < 900 ? true : false,
};
`

But if you resize the browser then I would want to re initialise the carousel with the updated parameters.

So if the browser is resized can I basically call mySwiper.update(); and it should re init the carousel with said parameters??

I tried this but mySwiper.update(); doesn't seem to work.

**Comment by kidjp85** [comment]
Hi @guideveloper , I don't think that will work because once you pass the params to create Swiper instance, you should update from Swiper instance. You can try using `rebuildOnUpdate` param to rebuild `Swiper`, but you need to let react component know to re-render when window size changes.
