### ISSUE TITLE
Swiper.off() not working correctly

### ISSUE THREAD

**Issue by illyas3** [kidjp85/react-id-swiper#240]
I am trying to stop event with: `this.swiper.swiper.off(event)`
It kinda works - event stops. But creates unwanted error msgs in console: `swiper.js:1102 Uncaught TypeError: events.split is not a function`.

So, I checked the implementation: 
```
SwiperClass.prototype.off = function off (events, handler) {
    var self = this;
    if (!self.eventsListeners) { return self; }

    events.split(' ').forEach(function (event) {
      console.log("for event")
      if (typeof handler === 'undefined') {
        self.eventsListeners[event] = [];
      } else if (self.eventsListeners[event] && self.eventsListeners[event].length) {
        self.eventsListeners[event].forEach(function (eventHandler, index) {
          if (eventHandler === handler) {
            self.eventsListeners[event].splice(index, 1);
          }
        });
      }
    });
    return self;
  };
```
`events` is my case it TouchEvent (`on: {touchMove: this.handleTouchMove}`), not a string, which explains the error msg. 
I've tried `this.swiper.swiper.off(event.toString())`, no error msg, but event doesn't stop as needed. 

How can I convert `event` in a way, that this function will accept it without errors? Did anyone encounter same issue?

**Comment by kidjp85** [comment]
@illyas3 , please try newest version and get `Swiper` instance from hooks example. Please let me know if u still face that issue
