### ISSUE TITLE
Pagination works incorrectly when clicking on bullets fast

### ISSUE THREAD

**Issue by scabbiaza** [kidjp85/react-id-swiper#244]
Watch the following gif:
![ezgif-3-71d85f2a70ed](https://user-images.githubusercontent.com/2734464/52999373-460e6800-342e-11e9-963e-76c24130b60f.gif)

I'm clicking on 1, 2, 3, 4, and you can see when I clicked "4" I was redirected to the slide 2 instead.

**Comment by kidjp85** [comment]
Hi @scabbiaza , could you still reproduce with the latest version ?

**Comment by marwej** [comment]
I have a similar problem with navigation with click on the slides. Related? (Can be seen after a few correct navigations in the image below.)
![Error in naviigation wiith click](https://user-images.githubusercontent.com/5296840/54594382-d392a700-4a30-11e9-99f5-36e14f642235.gif)

**Comment by antonramha** [comment]
@kidjp85, same behaviour on v2.1.2 =(

**Comment by Ritural** [comment]
@scabbiaza @antonramha @marwej 

Adding `touchEventsTarget: 'wrapper'` as a swiper option seemed to fix it for me :)

It was mentioned in this [comment](https://github.com/nolimits4web/swiper/issues/2428#issuecomment-478582316) on the Swiper GitHub issues.

**Comment by scabbiaza** [comment]
It seems to be working!
thank you, @Ritural !

**Comment by antonramha** [comment]
@Ritural awesome! thank you!

**Comment by Rehan-leilani** [comment]
anni diyaa code tery peo dyna c
