### ISSUE TITLE
scroll container swiper in reactjs did not work the scrollbar.

### ISSUE THREAD

**Issue by eyyyyyyy** [kidjp85/react-id-swiper#247]
i use scroll container wrapper. but i did not work. 

`import React from 'react'
import Swiper from 'react-id-swiper';

const params = {
    direction: 'vertical',
    slidesPerView: 'auto',
    freeMode: true,
    scrollbar: {
      el: '.swiper-scrollbar',
    },
    mousewheel: true,
    
  };

export default class Testimonial extends React.Component {
    
    render() {
        return (
            <div className="testimonial container">
                  <Swiper {...params}>
                  <div>Slide 1</div>
        <div>Slide 2</div>
        <div>Slide 3</div>
        <div>Slide 4</div>
        <div>Slide 5</div>
        <div>Slide 1</div>
        <div>Slide 2</div>
        <div>Slide 3</div>
        <div>Slide 4</div>
        <div>Slide 5</div>
        <div>Slide 1</div>
        <div>Slide 2</div>
        <div>Slide 3</div>
        <div>Slide 4</div>
        <div>Slide 5</div>
                   </Swiper>
            </div>
        )
    }
}`

![image](https://user-images.githubusercontent.com/43176076/53420959-bbbe9900-3a17-11e9-821d-3d61e599d798.png)

**Comment by kidjp85** [comment]
You should set the limit height for container to make scrolling feature work
