### ISSUE TITLE
Custom events & data setup for Navigation and Pagination outside the container

### ISSUE THREAD

**Issue by HectorLS** [kidjp85/react-id-swiper#248]
Hi

i have this setup with the version `"react-id-swiper": "^1.6.9"`
```jsx
const params = {
      shouldSwiperUpdate: true,
      spaceBetween: 20,
      speed: 600,
      slidesPerView: 'auto',
      pagination: {
        el: '.pagination--slider',
        type: 'custom',
        clickable: true,
        renderCustom: (swiper, current, total) => {
          return (
            <div className='pagination--slider' data-total={total} data-current={current}>
              <p>{total}</p>
            </div>
          );
        }
      },
      navigation: {
        nextEl: '.btn--next',
        prevEl: '.btn--prev'
      },
    }
```

But i see a ghost button displaying like this
```html
<div class="btn--prev" tabindex="0" role="button" aria-label="Next slide" aria-disabled="true"</div>
<div class="btn--next" tabindex="0" role="button" aria-label="Next slide" aria-disabled="false"</div>
```

While the custom ones are those two
```html
 <button type='button' className='btn--prev' onClick={this.goPrev}>Prev</button>
 <button type='button' className='btn--next' onClick={this.goNext}>Next</button>
```

and the returned pagination has no data-attr and an object [object object] inside.
```html
<div class="pagination--slider swiper-pagination-custom">[object Object]</div>
```
------------------------------

**So my questions are**

**1)** ¿How can i get the data change on my custom navigation & pagination components?
To be able to get aria-disabled true or false (for example)
and

**2)** ¿ how can i get a proper display of the pagination ?  with current and total slides data

i know they are silly questions but i have tried with any result 😢  thanks in advance

**Comment by kidjp85** [comment]
Hi @HectorLS , sorry for my late response. For  custom rendering, you should use provided render props functions like `renderPagination ` or `renderPrevButton `. Please try with Codesandbox environment I prepared in README. Please let me know if you still have trouble

**Comment by joebentaylor1995** [comment]
Is there any example of this? Struggling myself with this issue... @kidjp85
