### ISSUE TITLE
rebuildOnUpdate and shouldSwiperUpdate not work!

### ISSUE THREAD

**Issue by biggerbig** [kidjp85/react-id-swiper#250]
CODE is

componentDidMount() {
      this._getItems();
    }

_callApi = async () => {
      return fetch('URL')
      .then(response => response.json())
      .then(json => json.results)
      .catch(err => console.log(err))
    }

_getItems = async () => {
      const Datas = await this._callApi()
      this.setState({
        Datas
      })
    }

_renderItems =() => {
      const Datas = this.state.Datas.map(data => {
        return <Item
          key={data.id}
          title={data.title}
        />
      })
      return Datas
    }

render() {
      const NewStageCarousel = {
        slidesPerView: 'auto',
        centeredSlides: true,
        spaceBetween: 30,
        loop: true,
        autoplay: {
          delay: 2500,
          disableOnInteraction: false
        }
      };
    return (
        <Swiper {...NewStageCarousel} shouldSwiperUpdate> // or rebuildOnUpdate
            {this.state.Datas ? this._renderItems() : ''}
         </Swiper>
    )
}

Item render is fine. but Swiper is not working.
Actually, Swiper is working. But slide is no binding to Swiper.
Looks like, all items in a Slide.

I tried ref&update, different way to render, modify params and etc.. but still not work.

**Comment by kidjp85** [comment]
You should not initialise swiper content like that. Instead you should render swiper only data is available. For example

```javascript
this.state.Datas  ? <Swiper ....>{this._renderItems()}</Swiper> : null
```
