### ISSUE TITLE
Update two-way demo to remove legacy componentWillUpdate method

### ISSUE THREAD

**Issue by chicgeek** [kidjp85/react-id-swiper#251]
## Issue
The `componentWillUpdate` lifecycle method is set to be deprecated in React 17.0 and should be replaced with alternative approaches.

From this blog post: https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html

> One of the biggest lessons we’ve learned is that some of our legacy component lifecycles tend to encourage unsafe coding practices. They are:
> 
> * componentWillMount
> * componentWillReceiveProps
> * **_componentWillUpdate_**

**Note:** React 17.0 is still a fair ways off, but this is an easy change to make at any time.

## Current use
The `componentWillUpdate` lifecycle is used in the two-way gallery example:
http://kidjp85.github.io/react-id-swiper/#gallery

### Using componentWillUpdate

    componentWillUpdate(nextProps, nextState) {
      if (nextState.gallerySwiper && nextState.thumbnailSwiper) {
        const { gallerySwiper, thumbnailSwiper } = nextState

        gallerySwiper.controller.control = thumbnailSwiper;
        thumbnailSwiper.controller.control = gallerySwiper;
      }
    }

## Recommended change
I had a brief look and couldn't find an open repo to submit a pull request. Please point me in the right direction if I missed it.

### Using componentDidUpdate

    componentDidUpdate(prevProps, prevState) {
      const { gallerySwiper, thumbnailSwiper } = this.state
      if (gallerySwiper && thumbnailSwiper) {
        gallerySwiper.controller.control = thumbnailSwiper
        thumbnailSwiper.controller.control = gallerySwiper
      }
    }

**Comment by kidjp85** [comment]
Hi @chicgeek , thanks for your suggestion. I am planning to rewrite whole library with new hooks apis. That will be a breaking chance for version 2.x.

**Comment by chicgeek** [comment]
That's great news, hope the rewrite goes well.

I suggest this change be made to the docs anyway. This old method will eventually cause issues for anyone who upgrades to React 17 and doesn't update react-id-swiper.

It's a small change to the docs to update current best practice. Better yet, it might prevent some headaches in the future for users, as well as prevent a new issues for you to respond to. 😄

**Comment by MartinN3** [comment]
Im trying to rewrite Thumbs Gallery With Two-way Control into hooks but i kinda struggle 🗡 is there a chance anyone has it?
