### ISSUE TITLE
Cannot set property 'control' of undefined

### ISSUE THREAD

**Issue by shayandilz** [kidjp85/react-id-swiper#252]
import React, { Component } from "react";
import axios from "axios";
import "bootstrap/dist/css/bootstrap.min.css";
import Swiper from "react-id-swiper";

export default class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      apiUrl: API,
      original: [],
      thumbnail: [],
      gallerySwiper: null,
      thumbnailSwiper: null
    };
    this.galleryRef = this.galleryRef.bind(this);
    this.thumbRef = this.thumbRef.bind(this);
  }

  componentDidMount() {
    axios({
      url: (`${this.state.apiUrl}`),
      method: "post",
      data: JSON.stringify({ refresh: "true", editor_id: "13" })
    }).then(res => {
      this.setState({ original: res.data.output.items });
      this.setState({ thumbnail: res.data.output.items });
    });
  }

  componentWillUpdate(nextProps, nextState) {
    if (nextState.gallerySwiper && nextState.thumbnailSwiper) {
      const { gallerySwiper, thumbnailSwiper } = nextState;

      gallerySwiper.controller.control = thumbnailSwiper;
      thumbnailSwiper.controller.control = gallerySwiper;
    }
  }

  galleryRef(ref) {
    if (ref) this.setState({ gallerySwiper: ref.swiper });
  }

  thumbRef(ref) {
    if (ref) this.setState({ thumbnailSwiper: ref.swiper });
  }

  render() {
    const params = {
      containerClass: "action_itemsContainer",
      slidesPerView: 1,
      spaceBetween: 20,
      slidesPerGroup: 1,
      autoplay: true,
      loop: true,
      loopFillGroupWithBlank: false,
      rebuildOnUpdate: true,
      crossFade: true
    };
    const thumbnailParams = {
      containerClass: "action_itemsThumb",
      direction: "vertical",
      slidesPerView: 3,
      spaceBetween: 5,
      slidesPerGroup: 1,
      autoplay: true,
      loop: true,
      loopFillGroupWithBlank: false,
      rebuildOnUpdate: true
    };

    return (
      <React.Fragment>
        <div className="container">
          <div className="row">
            <div className="col">
              <Swiper {...params} ref={this.galleryRef}>
                {this.state.original.map((items, i) => {
                  return (
                    <div key={i.toString()}>
                      <img className="img_editors" src={items.thumb_url} />
                    </div>
                  );
                })}
              </Swiper>
            </div>
            <div className="col">
              <Swiper {...thumbnailParams} ref={this.thumbRef}>
                {this.state.thumbnail.map((items, i) => {
                  return (
                    <div key={i.toString()}>
                      <img className="thumb_editors" src={items.thumb_url} />
                    </div>
                  );
                })}
              </Swiper>
            </div>
          </div>
        </div>
      </React.Fragment>
    );
  }
}

**Comment by kidjp85** [comment]
You should render swiper only when `state. thumbnail ` and `state. original ` has data. Like 

```javascript
return this.state.thumbnail.length && this.state.original.length ? <div> </div>

return (
  <React.Fragment>
    <div className="container">
       { this.state.thumbnail.length && this.state.original.length &&
            (
<div className="row">
        <div className="col">
          <Swiper {...params} ref={this.galleryRef}>
            {this.state.original.map((items, i) => {
              return (
                <div key={i.toString()}>
                  <img className="img_editors" src={items.thumb_url} />
                </div>
              );
            })}
          </Swiper>
        </div>
        <div className="col">
          <Swiper {...thumbnailParams} ref={this.thumbRef}>
            {this.state.thumbnail.map((items, i) => {
              return (
                <div key={i.toString()}>
                  <img className="thumb_editors" src={items.thumb_url} />
                </div>
              );
            })}
          </Swiper>
        </div>
      </div>
             ) 
    </div>
  </React.Fragment>
);

```

**Comment by shayandilz** [comment]
sir i've tried what you suggested but still its only showing them, the control is not working!

**Comment by kidjp85** [comment]
@shayandilz , please provide live code demo from Codesanbox I provided in README. So I can have a closer look at your issue. Thanks

**Comment by shayandilz** [comment]
Thanks but I managed to solve it by removing the rebuildOnUpdate, that was the issue.
