### ISSUE TITLE
Module not found: Can't resolve 'Swiper'

### ISSUE THREAD

**Issue by mrkenng** [kidjp85/react-id-swiper#256]
Hi there! Just updated to the version 2.0.0 and I got this. ./node_modules/react-id-swiper/lib/ReactIdSwiper.js
Module not found: Can't resolve 'Swiper'

any idea?

**Comment by devbucket** [comment]
It seems like Swiper is now a peer dependency of react-id-swiper. You need to install it yourself.

**Comment by kidjp85** [comment]
@mrkenng , please check CHANGELOG. `Swiper` now has become `peer-dependency`. You need to install in separately
