### ISSUE TITLE
Unexpected token import with nextjs

### ISSUE THREAD

**Issue by rohmanhm** [kidjp85/react-id-swiper#259]
Got this error when using with nextjs.

```
/sandbox/node_modules/swiper/dist/js/swiper.esm.js:13
import { $, addClass, removeClass, hasClass, toggleClass, attr, removeAttr, data, transform, transition as transition$1, on, off, trigger, transitionEnd as transitionEnd$1, outerWidth, outerHeight, offset, css, each, html, text, is, index, eq, append, prepend, next, nextAll, prev, prevAll, parent, parents, closest, find, children, remove, add, styles } from 'dom7/dist/dom7.modular';
^^^^^^

SyntaxError: Unexpected token import
```

Here's the sandbox:
https://codesandbox.io/s/k29xjy98j3?fontsize=14

**Comment by estepanov** [comment]
Also just encountered this. I found another issue on this repo with `Unexpected token import` and next.js but that error pointed to issue with importing React. The import error you reference here is the same one I am getting.  
```
/Users/evans/Work/newWebApp/client/node_modules/swiper/dist/js/swiper.esm.js:13
import { $, addClass, removeClass, hasClass, toggleClass, attr, removeAttr, data, transform, transition as transition$1, on, off, trigger, transitionEnd as transitionEnd$1, outerWidth, outerHeight, offset, css, each, html, text, is, index, eq, append, prepend, next, nextAll, prev, prevAll, parent, parents, closest, find, children, remove, add, styles } from 'dom7/dist/dom7.modular';
```
All my packages are point to the latest versions.

**Comment by kidjp85** [comment]
The issue here is related to es module transpile issue from Next. It's still not fixed yet.
https://github.com/zeit/next.js/issues/706. For now there are 2 temporary solutions here:
1. Using [next-transpile-modules](https://github.com/martpie/next-transpile-modules)
2. Releasing v2.1.1, to let u guys use full transpiler version of Swiper.

**Comment by faizyukstay** [comment]
Thanks for anyone involve on creating this library, it really help me alot.

@kidjp85 i am using create react app with `yarn build && yarn serve` command and encounter this problem too, here is the error:

```/Users/fullstuckdeveloper/yukstay-web/node_modules/swiper/dist/js/swiper.esm.js:13
import { $, addClass, removeClass, hasClass, toggleClass, attr, removeAttr, data, transform, transition as transition$1, on, off, trigger, transitionEnd as transitionEnd$1, outerWidth, outerHeight, offset, css, each, html, text, is, index, eq, append, prepend, next, nextAll, prev, prevAll, parent, parents, closest, find, children, remove, add, styles } from 'dom7/dist/dom7.modular';
       ^

SyntaxError: Unexpected token {
    at new Script (vm.js:84:7)
    at createScript (vm.js:264:10)
    at Object.runInThisContext (vm.js:312:10)```

**Comment by faizyukstay** [comment]
i manage to fix it by ignoring `dom7` and `swiper` on babel configuration.
here is my code..
reference: https://github.com/nolimits4web/Swiper/issues/2335

<img width="460" alt="Screen Shot 2019-03-16 at 23 16 56" src="https://user-images.githubusercontent.com/46273747/54478147-c6639580-4841-11e9-880f-af8b128009e8.png">

**Comment by rohmanhm** [comment]
@kidjp85 Could you provide an example to use with `next-transpile-modules`?
That's gonna help a lot

**Comment by kidjp85** [comment]
@rohmanhm , [here](https://codesandbox.io/s/kxx0ympjmv?fontsize=14) you are

**Comment by rohmanhm** [comment]
Thanks, @kidjp85 
That works

**Comment by rossenv** [comment]
@kidjp85
I'm trying to use next-transpile-modules but this is the  error now...

![image](https://user-images.githubusercontent.com/4202236/54586622-4a767280-4a26-11e9-8a03-efd78462de4f.png)

my next.config.js looks like this 
`module.exports = withTM(
  withCSS(
    withImages(
      withTypescript({
        webpack(config, options) {
          // Do not run type checking twice:
          if (options.isServer) config.plugins.push(new ForkTsCheckerWebpackPlugin());

          config.resolve.modules.unshift(__dirname);

          return config;
        },
        transpileModules: ['swiper', 'dom7'],
      })
    )
  )
);`

**Comment by rohmanhm** [comment]
I'm still getting the error too when using it with typescript project.

**Comment by rohmanhm** [comment]
> Releasing v2.1.1, to let u guys use full transpiler version of Swiper.

Full transpiler version of Swiper is not a problem for me.

**Comment by nghiepit** [comment]
Same the problem with @rossenv

**Comment by parkerhutchinson** [comment]
#268 trying to get some movement on this as its causing issues with jest as well.

**Comment by kidjp85** [comment]
@all, I released `2.1.1` which support full version. You can import full version by `react-id-swiper/lib/ReactIdSwiper.full`

**Comment by rossenv** [comment]
Hi, but now when I add:
**import { Navigation } from 'swiper/dist/js/swiper.esm';**
the error is:

![image](https://user-images.githubusercontent.com/4202236/54977101-fb3fbd00-4fa4-11e9-8c39-4605b0841c0f.png)

**Comment by nghiepit** [comment]
I tried to test `2.1.1` and decided downgrade to `1.6.9` 😭

**Comment by rossenv** [comment]
Ooops, I just realized that no need to import from **swiper/dist/js/swiper** when we have **ReactIdSwiper.full**... In other words we can import Navigator etc. like this:

**import Swiper, { Navigation } from 'react-id-swiper/lib/ReactIdSwiper.full';** 

@kidjp85 fix your examples too pls.
@nghiepit  I think there is no need to downgrade ...for now  ;)

**Comment by NeroCor** [comment]
If you have Problems with your Jest Tests e.g.

```
/.../node_modules/swiper/dist/js/swiper.esm.js:13
    import { $, addClass, removeClass, hasClass, toggleClass, attr, removeAttr, data, transform, transition as transition$1, on, off, trigger, transitionEnd as transitionEnd$1, outerWidth, outerHeight, offset, css, each, html, text, is, index, eq, append, prepend, next, nextAll, prev, prevAll, parent, parents, closest, find, children, remove, add, styles } from 'dom7/dist/dom7.modular';
           ^
    SyntaxError: Unexpected token {
```

My Solution was to let Jest transform the swiper dependencies.
In Jest Config add:
```
transformIgnorePatterns: [
    "/node_modules/(?!swiper|dom7/.*)",
  ],
```

**Comment by rossenv** [comment]
Syntax error in ie11

```
-> class Dom7 ....
```
I give up and will downgrade to 1.6.9 :(

**Comment by kidjp85** [comment]
@rossenv  for the full version you don't have to include anything from swiper libs. Just use it like `1.6.9`

**Comment by rossenv** [comment]
@kidjp85 Could you give me an example how to import **Swiper, Pagination, Navigation** in **nextjs** which work in major browsers plus ie11?

**Comment by bautistaaa** [comment]
> If you have Problems with your Jest Tests e.g.
> 
> ```
> /.../node_modules/swiper/dist/js/swiper.esm.js:13
>     import { $, addClass, removeClass, hasClass, toggleClass, attr, removeAttr, data, transform, transition as transition$1, on, off, trigger, transitionEnd as transitionEnd$1, outerWidth, outerHeight, offset, css, each, html, text, is, index, eq, append, prepend, next, nextAll, prev, prevAll, parent, parents, closest, find, children, remove, add, styles } from 'dom7/dist/dom7.modular';
>            ^
>     SyntaxError: Unexpected token {
> ```
> 
> My Solution was to let Jest transform the swiper dependencies.
> In Jest Config add:
> 
> ```
> transformIgnorePatterns: [
>     "/node_modules/(?!swiper|dom7/.*)",
>   ],
> ```

I'm still having issues even with this
```
    import { $, addClass, removeClass, hasClass, toggleClass, attr, removeAttr, data, transform, transition as transition$1, on, off, trigger, transitionEnd as transitionEnd$1, outerWidth, outerHeight, offset, css, each, html, text, is, index, eq, append, prepend, next, nextAll, prev, prevAll, parent, parents, closest, find, children, filter, remove, add, styles } from 'dom7/dist/dom7.modular';
           ^

    SyntaxError: Unexpected to {

      3 | import PropTypes from 'prop-types';
      4 | import styled from 'styled-components';
    > 5 | import { Swiper, Keyboard } from 'swiper/js/swiper.esm';
```
did you have to add anything to your `transform` section @and-who ?

my jest config
```
  transform: {
    '\\.(gql|graphql)$': 'jest-transform-graphql',
    '^.+\\.(js)$': 'babel-jest',
  },
  transformIgnorePatterns: ['/node_modules/(?!swiper|dom7/.*)'],
```
