### ISSUE TITLE
activeSlideKey doesn't work in loop

### ISSUE THREAD

**Issue by devbucket** [kidjp85/react-id-swiper#260]
Currently, I came across an issue with setting the `activeSlideKey` prop. In my case, the value for this prop is set dynamically based on some user configuration. However, because of this line of code

```js
// In loop mode first slide index should be 1
let id = loop ? 1 : 0;
```

in lines 67 and 68, the swiper ends up showing the slide BEFORE the one that it should be.

When it happens to be the first slide (index 0), one ends up at the last slide instead.

**Comment by kidjp85** [comment]
Hi @devbucket , can you check this [live code](https://codesandbox.io/s/pm638nvy30) . I think it works well with current logic
