### ISSUE TITLE
The slider doesn't display and work properly on first display

### ISSUE THREAD

**Issue by themevan** [kidjp85/react-id-swiper#261]
Hi

First of all, check my live demo https://ui.mofect.com/moblog  the top slider doesn't display properly, I have set slidesPerView to 2, but it only displays 1 and can't be scrolled. But when I resize the window size, it works like a charm.

I have read this similar issue https://github.com/kidjp85/react-id-swiper/issues/185 but no solution for me. Here are my codes:

```
import React, { Component } from 'react';
import { Link } from 'react-router-dom';
import Swiper from 'react-id-swiper';
import SliderItem from '../../components/slider-dom';
import { Pagination } from 'swiper/dist/js/swiper.esm'

/* SlideShow */
class Slider extends Component{

  constructor(props){
    super(props);
    this.state = {
       data: [],
    }
  }

  componentDidMount() {
     this.loadSlider();
  }

  loadSlider = () => {
     const { data } = this.state;

     const url = `https://xxxxxxxxxxx/`;
     fetch(url)
       .then((response) => {
          return response.json()
        })
       .then(json => {
         this.setState({
           data: json,
         });
         
       })
       .catch(function() {
     });
  };

  loop = () => {
    let loop = [];

    this.state.data.length > 0 && this.state.data.map((slide, i) => {

          loop.push(
            <SliderItem 
              key={ i } 
              id={ slide.id }
              postType={ slide.post_type }
              postID={ slide.post_id }
              pageID={ slide.page_id }
              productID={ slide.product_id }
              title={ slide.title }
              image={ slide.image }
              description={ slide.description }
            />
         );
    });
    return loop;
  }

  render() {
    const params = {
      slidesPerView: 2,
      loop: true,
      spaceBetween: 10,
      modules: [Pagination],
      shouldSwiperUpdate: true,
      rebuildOnUpdate: true,
      pagination: {
        el: '.swiper-pagination',
        type: 'bullets',
        clickable: true
      }
    }

    return(
      <div className="mo-slider">
          { this.state.data &&
            <Swiper { ...params} >
              { this.loop() }
            </Swiper>
          }
      </div>
    );
  }
}

export default Slider;
```
Anything I missed?

**Comment by biggerbig** [comment]
<div> 형식이 아닌 컴포넌트 형식은 작동하지 않습니다. <div> 형식으로 랜더링 되게 작성하면 해결 됩니다.

Component formats other than <div> will not work. You can do this by creating a rendering in the <div> format.

Use translation app.

**Comment by biggerbig** [comment]
NOT:
```
<Swiper>
    <SliderItem />
</Swiper>
```

YES:
```
<Swiper>
    <div>Something</div>
</Swiper>
```

컴포넌트 형태로 랜더링 하면 실제 마크업은 div로 표시되지만 스와이퍼는 div로 인식하지 않습니다. SliderItem 이라는 엘리먼트로 인식하는거 같습니다.
저도 같은 문제가 있었는데 div로 랜더링 되게 하면 동작합니다..

When render in component form, the actual markup is displayed as div, but the swipe is not recognized as div. It is recognized as an element called SliderItem.

I had the same problem. However, it works when it is render with div.

I'm sorry to use the translator.

**Comment by RichardLindhout** [comment]
Looks like rebuildOnUpdate: true, should always be set true

**Comment by shafaqat309** [comment]
any help please, I m having the same issue,

**Comment by ndotmdot** [comment]
I had the same issue und found a workaround. 

I think the problem is that the swiper initialization happens before it is rendered to the DOM and thus it sets wrong values for width and hight etc. 

You can manually update the swiper when you are sure that everything is renderd to the DOM like so:

`useEffect(() => {
    let timeout ;
    if (swiper !== null) {
      timeout = setTimeout(() => swiper.update(), 500)
    }
    return () => {
      clearTimeout(timeout)
    }
  },[swiper])`

More elegant solutions are very welcome.

**Comment by NguyenQuangVinh123** [comment]
I have that issue too. Some one help me plz...

**Comment by Decoder3-14** [comment]
For anyone that is still searching for the solution, just make sure the length of the array of items is bigger than 0, here is how it is solved in one of the issues: https://github.com/kidjp85/react-id-swiper/issues/185`

**Comment by configbug** [comment]
> Tuve el mismo problema y encontré una solución.
> 
> Creo que el problema es que la inicialización de swiper ocurre antes de que se procese en el DOM y, por lo tanto, establece valores incorrectos para ancho y altura, etc.
> 
> Puede actualizar manualmente el swiper cuando esté seguro de que todo se procesa en el DOM de la siguiente manera:
> 
> ```
> useEffect(() => {
>     let timeout ;
>     if (swiper !== null) {
>       timeout = setTimeout(() => swiper.update(), 500)
>     }
>     return () => {
>       clearTimeout(timeout)
>     }
>   },[swiper])
> ```
> 
> Las soluciones más elegantes son muy bienvenidas.
> 
> Sistema:
> "gatsby": "^ 2.13.29"
> "react-id-swiper": "^ 2.3.2"

What's swiper ??  Maybe you could put the complete code? :-)

**Comment by kidjp85** [comment]
I think here is the issue

```
 return(
      <div className="mo-slider">
          { this.state.data &&
            <Swiper { ...params} >
              { this.loop() }
            </Swiper>
          }
      </div>
    );
```

You should set the condition to `this.state.data.length > 1`

**Comment by sdg850** [comment]
in my case, the problem was resolved using the parameter "observer" ( Set to true to enable Mutation Observer on Swiper and its elements. In this case Swiper will be updated (reinitialized) each time if you change its style (like hide/show) or modify its child elements (like adding/removing slides))
src: https://swiperjs.com/swiper-api 

          <Swiper
                // className='swiper-container'
                tag='section'
                wrapperTag='ul'
                spaceBetween={30}
                slidesPerView='5'
                autoplay= {true}
                centeredSlides= 'true'
                //loop = 'false'
                navigation
                pagination               
                onInit={swiper => { console.log('Swiper initialized!', swiper) }}
                effect='coverflow'
                onSwiper={(swiper) => console.log(swiper)}
                onSlideChange={() => console.log('slide change')}
                className = 'swiper-container'
                //shouldSwiperUpdate
                //rebuildOnUpdate
                observer
            >

**Comment by manishtomarleo21** [comment]
In my case its worked as soon as i passed key props as attribute.
