### ISSUE TITLE
How to get ref on version 2.1.0

### ISSUE THREAD

**Issue by d4n1b** [kidjp85/react-id-swiper#263]
I'm struggling to do the same that you suggested here https://github.com/kidjp85/react-id-swiper/issues/241 in order to get the ref.

I want to access the `activeIndex` property.

Any suggestion?

**Comment by kidjp85** [comment]
From `2.0.0` , `react-id-swiper` is no longer using ReactComponent. It was rewritten with FunctionComponent to use `hooks` api, therefore you can't get ref . Instead, there is new prop name `getSwiper` to get `Swiper` instance incase you need to manipulate swiper outside of Swiper component. You can find live demo [here](https://codesandbox.io/s/p8j61y7j7?fontsize=14)

**Comment by d4n1b** [comment]
Thanks for the fast reply!!

**Comment by chrisalcantara** [comment]
Hello! I'm interested in seeing an example, but the link doesn't seem to include code relevant to this question.

**Comment by 88mpg** [comment]
> Hello! I'm interested in seeing an example, but the link doesn't seem to include code relevant to this question.

I think @kidjp85 means [this example](https://react-id-swiper.ashernguyen.site/example/manipulating-component-outside-swiper).

**Comment by IlyaZolotarev** [comment]
> > Hello! I'm interested in seeing an example, but the link doesn't seem to include code relevant to this question.
> 
> I think @kidjp85 means [this example](https://react-id-swiper.ashernguyen.site/example/manipulating-component-outside-swiper).

This is the same story. Need an example of getSwiper props.
