### ISSUE TITLE
Ref Issue since Update to 2.1

### ISSUE THREAD

**Issue by arturhenryy** [kidjp85/react-id-swiper#264]
Hey i get the following error since updating
i am using a useRef hook here

Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

How to handle refs with swiper now?

**Comment by Eugene-Sviridov** [comment]
@arturhenryy Hi. Please try ```getSwiper``` props

**Comment by kidjp85** [comment]
@arturhenryy , you can find answer here https://github.com/kidjp85/react-id-swiper/issues/263

**Comment by arturhenryy** [comment]
@kidjp85 thanks i solved it using the state instance of swiper already. i think it would be useful for others to mention this explicitly under breaking changes.
