### ISSUE TITLE
Extend swiper configuration, multiple instances on page, controls mixed

### ISSUE THREAD

**Issue by ntucakovic** [kidjp85/react-id-swiper#265]
This isn't a bug per se, but I'm not sure what to make of it. You decide :) Maybe update the documentation for it?

I've got bunch of swipers, with ton of shared config. So I though to create a default config and extend/override accordingly.

I defined a default config in which I load the most common modules, for instance `Pagination` and `Navigation` and add the initialization parameters for `pagination` and `navigation` keys.

I then create a new config, which extends previous one, and I decide to override modules by only adding `Pagination` for instance. (I leave the `pagination` and `navigation` keys in place from previous config, don't override them).

That setup will have issues when there are multiple instances of swiper in place. 
Demo which highlights the issue: https://codesandbox.io/s/v10v4rprwy

I now know that I should also reset `pagination` and `navigation` keys when mentioned modules are removed from a specific config so it doesn't behave like that.

Not sure what to make of it, whether you should do something about it, or just add a label won't fix or something so future searches can find this issue.

**Comment by kidjp85** [comment]
Hi @ntucakovic , you should not share `Swiper` instance like this. Each swiper should only have one instance. You can refer the change I update [here](https://codesandbox.io/s/m3q847x1x)

**Comment by cyruskong1** [comment]
@kidjp85 what about multiple swipers? I am facing this issue as well 
` <div className={className}>
      <Swiper {...swiperParams} >
        {images.map(image => (
          <Image
            src={image.url}
            key={`swiper-side-${image.key}`}
            className='swiper-pagination'
          />
        ))}
      </Swiper>
      <div className='test' />
    </div>
`

and it gets called like this 
`
{arrayOfBuckets.map( bucket => (
        <AuctionCard
          images={bucket.images}
          id={bucket.resource_id}
          key={bucket.resource_id}
        />
      ))}
`

im seeing the same issue when clicking on the bullets

**Comment by sebil** [comment]
> Hi @ntucakovic , you should not share `Swiper` instance like this. Each swiper should only have one instance. You can refer the change I update [here](https://codesandbox.io/s/m3q847x1x)

@kidjp85 can you please show the code example how to deal with multiple instances? The codesandbox link is not available anymore.

I have a Swiper that works all fine, but when I initialize a second swiper inside a modal dialog, it gets initialized correctly but the swiping, buttons and pagination does not work. Can you help?
