### ISSUE TITLE
Duplicate image loading.

### ISSUE THREAD

**Issue by AuthorProxy** [kidjp85/react-id-swiper#266]
Duplicate image loading on first init and on every swipe, checked with lazy load: true
You can see it here at chrome network console: https://codesandbox.io/s/j27960ry75

**Comment by kidjp85** [comment]
Hi @AuthorProxy , this is `Swiper`'s issue not with `React-Id-Swiper`. You can reproduce from Swiper demo page too.  I think you should raise this issue with Swiper team :)

**Comment by AuthorProxy** [comment]
As you see I am already.
