### ISSUE TITLE
Syntax error with nextjs

### ISSUE THREAD

**Issue by pmg1989** [kidjp85/react-id-swiper#274]
I just upgraded to the latest version and found this error.

/node_modules/swiper/dist/js/swiper.esm.js:13
import { $, addClass, removeClass, hasClass, toggleClass, attr, removeAttr, data, transform, transition as transition$1, on, off, trigger, transitionEnd as transitionEnd$1, outerWidth, outerHeight, offset, css, each, html, text, is, index, eq, append, prepend, next, nextAll, prev, prevAll, parent, parents, closest, find, children, remove, add, styles } from 'dom7/dist/dom7.modular';

**Comment by kidjp85** [comment]
You can find the solution here https://github.com/kidjp85/react-id-swiper/issues/259
