### ISSUE TITLE
Swiper prop "effect" doesn't work

### ISSUE THREAD

**Issue by samueldepooter** [kidjp85/react-id-swiper#278]
None of the effect values seem to work?
Sandbox: https://codesandbox.io/s/53m71wjk9x

**Comment by ntucakovic** [comment]
You're missing `EffectFade` in the modules list.

https://codesandbox.io/s/n72mlqn8vm

**Comment by samueldepooter** [comment]
> You're missing `EffectFade` in the modules list.
> 
> https://codesandbox.io/s/n72mlqn8vm

Aha totally missed that module. Thanks!
