### ISSUE TITLE
Mousewheel doesn't work

### ISSUE THREAD

**Issue by Sprinter100** [kidjp85/react-id-swiper#279]
Mousewheel prop doesn't seem to do anything if I use react-id-swiper.
If I use swiper.js without react-id-swiper, then everything is working.

https://codesandbox.io/s/yqyyk8kqxj - here is a swiper.js example. Mouse wheel is working.

https://codesandbox.io/s/9486w38yxw - and this is a react-id-swiper version. Mousewheel doesn't work.

**Comment by kila03** [comment]
[Read docs here](https://idangero.us/swiper/api/#custom-build)

**Comment by kidjp85** [comment]
@Sprinter100 , you should include `Mousewheel ` in modules to make it work.
