### ISSUE TITLE
rebuildOnUpdate is not working in Thumbs Gallery with Two-way Control on RTL

### ISSUE THREAD

**Issue by shivaMohan1995** [kidjp85/react-id-swiper#280]
This is my error

TypeError: Cannot set property 'control' of undefined
ourHotelsGallerySwiper.componentWillUpdate
./components/home/ourHotelsGallerySwiper.jsx:50
  47 | componentWillUpdate(nextProps, nextState) {
  48 | 	if (nextState.gallerySwiper && nextState.thumbnailSwiper) {
  49 | 		const { gallerySwiper, thumbnailSwiper } = nextState
> 50 | 		gallerySwiper.controller.control = thumbnailSwiper;
  51 | 		thumbnailSwiper.controller.control = gallerySwiper;
  52 | 	}
  53 | }
[swiperIssue.txt](https://github.com/kidjp85/react-id-swiper/files/3080164/swiperIssue.txt)

**Comment by kidjp85** [comment]
You can refer code [here](https://codesandbox.io/s/5xyx4lz3vn)

**Comment by shivaMohan1995** [comment]
In that example images are not displaying swiper
