### ISSUE TITLE
Two-way control is not working

### ISSUE THREAD

**Issue by IndigoHollow** [kidjp85/react-id-swiper#284]
Hello, thank you for your wonderful component!

I'm trying to make a carousel with thumbs, but it seems that controls doesn't work properly. Could you please see demo? Thank you in advance.

[https://codesandbox.io/s/74mz4jz646](url)

**Comment by kidjp85** [comment]
Hi @IndigoHollow , `ref` is no longer used cause ReactIdSwiper now is function. Sorry for not update demo page. You can refer working version [here](https://codesandbox.io/s/5xyx4lz3vn)

**Comment by IndigoHollow** [comment]
Thank you for the answer. Now thumbs are related with the main Swiper. But it works really strange: click on the last thumb updates the first Swiper and click on the middle thumb do nothing at all. Could you please tell me which way to dig to? Really need to solve the problem.
