### ISSUE TITLE
better example code on http://kidjp85.github.io/react-id-swiper/

### ISSUE THREAD

**Issue by loveky** [kidjp85/react-id-swiper#288]
Since 2.1.1, features like Autoplay, Pagination and etc requires user manually loading corresponding module. But this is not reflected in example code, for example:

<img width="669" alt="Snipaste_2019-04-29_09-14-43" src="https://user-images.githubusercontent.com/1198651/56872787-5f9be380-6a5f-11e9-9c08-2917968f3f1d.png">

Maybe we can update these example code to include those modules like in the project's README.md file.

**Comment by kidjp85** [comment]
Hi @loveky , new demo page has been released. Please check.
