### ISSUE TITLE
The effect parameter is ignored by the compact version

### ISSUE THREAD

**Issue by kkomelin** [kidjp85/react-id-swiper#289]
Please take a look at the demo:
https://codesandbox.io/s/rlznyr2r0p

The problem only occurs when I use the 'compact' version:
```javascript
import Swiper from "react-id-swiper";
```

And it utilizes parameters properly when I use the full version:
```javascript
import Swiper from 'react-id-swiper/lib/ReactIdSwiper.full';
```

**Comment by kidjp85** [comment]
@kkomelin , u need to add module `EffectFade` to make it work. [Here](https://codesandbox.io/s/qql9yqq0x4) is the working version

**Comment by kkomelin** [comment]
Thank you @kidjp85 for your help. Where can I read about other available plugins?
