### ISSUE TITLE
documentation update for autoplay

### ISSUE THREAD

**Issue by mingthegit** [kidjp85/react-id-swiper#291]
Thanks for your great library, I use if for every React project.

It would be great if you can add section for `autoplay` to documentation.
I was trapped to troubleshoot autoplay not working and it turned out that we should add it to `modules`.

```
import { Autoplay } from "swiper/dist/js/swiper.esm";
...
const swiperParams = {
  ...
  modules: [Autoplay],
  ...
};
```

**Comment by ddinggu** [comment]
Thank you for this comment!

I solve the problem not worked autoplay.

**Comment by kidjp85** [comment]
I just released new documentation page. Please check
