### ISSUE TITLE
Fade effect isn't working with version 2.1.2

### ISSUE THREAD

**Issue by supahfunk** [kidjp85/react-id-swiper#293]
Fade effect doesn't work with params: { effect: 'fade' }
Sandbox here: https://codesandbox.io/s/ym69pl3w7v

**Comment by kidjp85** [comment]
For version 2.1.2 , you need to include module to use Fade effect. Or upgrade to newest version 2.3.1

**Comment by sebastianschrama** [comment]
I have the same result with `"react-id-swiper": "^3.0.0"` / `"swiper": "^5.4.5`
