### ISSUE TITLE
Version problem

### ISSUE THREAD

**Issue by lemondreamtobe** [kidjp85/react-id-swiper#295]
version of my react is "16.5.2"
but i add the react-id-swiper version is 2.1.2 and the swiper version is ^4.5.0
so it throw error
![image](https://user-images.githubusercontent.com/22766436/58295636-e778d180-7e02-11e9-8bc7-5559e568c244.png)

i use them as follow
![image](https://user-images.githubusercontent.com/22766436/58295645-f52e5700-7e02-11e9-9c19-2d10b6a0652e.png)
![image](https://user-images.githubusercontent.com/22766436/58295657-fcedfb80-7e02-11e9-9d0d-c75df23fff9f.png)
![image](https://user-images.githubusercontent.com/22766436/58295664-024b4600-7e03-11e9-9151-1085b4efbb76.png)
i want to fix them? maybe your can provide a useable version?

**Comment by JoseChirinos** [comment]
For this version (2.1.2) requires React & ReactDOM ver >=16.8.0, 
if you use yarn use this:
`yarn upgrade react@latest`
