### ISSUE TITLE
slidesPerColumn param update does not correctly render slides

### ISSUE THREAD

**Issue by andrewjslack** [kidjp85/react-id-swiper#298]
CodeSandbox: https://codesandbox.io/s/reactidswiper-slidespercolumn-update-issue-bww36?fontsize=14

**What you did**
I am updating the slidesPerColumn param on window resize and re-rendering Swiper component with shouldSwiperUpdate set to true eg:

```
  useEffect(
    () => {
      if (swiper !== null) {
        swiper.on("resize", () => {
          if (window.innerWidth < 1024) {
            swiper.params.slidesPerColumn = 1
            swiper.params.slidesPerView = 1
          } else {
            swiper.params.slidesPerColumn = 3
            swiper.params.slidesPerView = 2
          }
          swiper.update();
        });
      }
    },
    [swiper]
  );
```

**Expected Behavior**
Swiper should display 3 slides per column inside the Swiper container when window size > 1024

**Actual Behavior**
Swiper displays only 1 slide per column at 100% of container height. 
slidesPerView renders correctly

**Comment by kidjp85** [comment]
@andrewjslack , you forgot to set slide per page when `Swiper` instance is defined.

[Here](https://codesandbox.io/s/reactidswiper-slidespercolumn-update-issue-jzozr) is working version

**Comment by andrewjslack** [comment]
That does not solve the issue described. I attach a screenshot of your example CodeSandbox displaying the same issue described originally.

<img width="1782" alt="Screenshot 2019-05-31 at 08 49 02" src="https://user-images.githubusercontent.com/32870693/58690317-2ff33a80-8381-11e9-99aa-899f3ca3a62a.png">

**Comment by andrewjslack** [comment]
Taking a look at the parameters it seems as though they are being updated to the correct value however the layout is not updating to fit the slides in a column. I also tried using rebuildOnUpdate but have the same issue.

Additionally, I am experiencing an issue raised in the Swiper repo where slides are not ordered correctly in a column layout:
https://github.com/nolimits4web/swiper/issues/2824

Could it be a related problem to do with the ordering of the slides in the flexbox?

**Comment by andrewjslack** [comment]
I have got it working on page load by setting init: false and then setting params before calling swiper.init() 

eg:

````
  const setSlidePerColumn = swiper => () => {
    if (window.innerWidth < 1024) {
      swiper.params.slidesPerColumn = 1
      swiper.params.slidesPerView = 1
    } else {
      swiper.params.slidesPerColumn = 3
      swiper.params.slidesPerView = 2
    }
    swiper.init()
  }

  useEffect(() => {
    if (swiper !== null) {
      swiper.on('init', setSlidePerColumn(swiper))
      ....
    }
  }, [swiper])
````

However, it still does not update responsively on resizing and I am not sure how to handle this. I don't think to destroy and recreate the swiper on each resize is feasible. Even if setting a timeout and waiting for a 'done resizing' event.

**Comment by ehssamimi** [comment]
the answer is [here](https://github.com/kidjp85/react-id-swiper/issues/55#issuecomment-306380362)
