### ISSUE TITLE
Accessibility issues in 2.x

### ISSUE THREAD

**Issue by fakhrizaki** [kidjp85/react-id-swiper#303]
### Pagination in version 1.6.5
http://kidjp85.github.io/react-id-swiper/

![react-id-swiper-v1 6 5](https://user-images.githubusercontent.com/3256654/60230302-c01d9480-98d9-11e9-9213-bc799f1c6a09.PNG)

### Pagination in version 2.1.0
https://codesandbox.io/s/p8j61y7j7

![react-id-swiper-v2 1 0](https://user-images.githubusercontent.com/3256654/60230658-083cb700-98da-11e9-8f0a-7d39b9650cb8.PNG)

Please correct me if I am missing anything.

Thanks!

**Comment by kidjp85** [comment]
Hi @fakhrizaki , I don't think that is react-id-swiper's issue. If you check newest demo page for 2.3.1 https://react-id-swiper.ashernguyen.site/example/pagination.
