### ISSUE TITLE
Append slides with react components

### ISSUE THREAD

**Issue by ZachBublil** [kidjp85/react-id-swiper#306]
I want to append slides to my swiper which every cell would be a react component and not a html element string.
I tried to use the rendertoString method to get the string element from my component but it doesn't work. In addition, if I add an empty div as a string html, the swiper slide to index 0 for some reason.

**Comment by jere-co** [comment]
You don't need to append, React will render the component again for you. You can save the current index with `useState` if you wish to stay in the same slide after the re-render. 

I personally have a component that loops over `React children` - sounds like this could be handy for your use-case as well (consider having a better key than the `sliceIndex` if possible though):  
```Javascript 
<Swiper {...config}>
  {children.map((Child, sliceIndex) => (
    <div key={sliceIndex}>
      {Child}
    </div>
  ))}
</Swiper>
```
