### ISSUE TITLE
Broken hooks rules

### ISSUE THREAD

**Issue by froziq** [kidjp85/react-id-swiper#307]
Hi! Recently i update from 1.6.9 to 2.3.1 and faced with hooks rules problem that provides by eslint inside ReactIdSwiper.
Do you advice me to disable eslint rules or anything else?
Thx!
![image](https://user-images.githubusercontent.com/33020166/60446546-44e61680-9c2a-11e9-891d-b03a0233ed92.png)

**Comment by kidjp85** [comment]
Hi @froziq , what React version are you using ?

**Comment by wudiansi** [comment]
> Hi @froziq , what React version are you using ?

Hi there,
i've get the same problem, and my React version is 16.7.0

**Comment by wudiansi** [comment]
well, i think i figure it out.
cause i used dynamic  data from backend, but did't get right init when data's length got 0. for map return a ''.
this is my own problem.
hope to help people who have similar problems.😃

**Comment by froziq** [comment]
hi @kidjp85. i'm using latest version of React. for now it 16.8.6.

**Comment by kidjp85** [comment]
It should be gone with the newest version.
