### ISSUE TITLE
Swiper shows all slides at once, instead of separate slides

### ISSUE THREAD

**Issue by bnikom** [kidjp85/react-id-swiper#309]
When i implement the most basic version of Swiper, i get the first slide to display ALL of the slides rather than just the first one. I have attached a codesandbox below. It seems to calculate the height as all the slides together?

https://codesandbox.io/s/blissful-lake-7tpw2?fontsize=14

**Comment by kidjp85** [comment]
You need to load swiper stylesheet. Please read documentation.
