### ISSUE TITLE
Events don't see swiper instance

### ISSUE THREAD

**Issue by kurtnovack** [kidjp85/react-id-swiper#316]
I based this example off of the getSwiper feature and added a simple event.
```js
on: {
  slideChange: () => {
    console.log(swiper);
  }
}
```
It looks likes the params are loaded in first and NOT updated so the `swiper` state always remains null.
(check the console while running this)

https://codesandbox.io/embed/reactidswiper-demo-qot2f

Is this a bug or is there a quick workaround to fix this?

**Comment by kidjp85** [comment]
Hi @kurtnovack , you can't get swiper instance value from `on` event from params. Instead, you should add event listener from `useEffect`.

**Comment by lauterry** [comment]
Hi @kidjp85 

Do you mean ? : 

```
const [swiper, setSwiper] = useState(null);

useEffect(() => {
	swiperParams.on. slideChange = () => {
		console.log(swiper);
	};
}, [swiper]);
```
