### ISSUE TITLE
Doesn't work on Internet Explorer??

### ISSUE THREAD

**Issue by oelbaganwg** [kidjp85/react-id-swiper#317]
Has anyone noticed that react-id-swiper simply doesn't work or load on Internet Explorer. I've tried and it works everywhere, except on IE I get a blank page. 

Even if you load the demo site on IE it's broken.
https://kidjp85.github.io/react-id-swiper/

Is there anyway to make this compatible with IE?

**Comment by wuzinong** [comment]
Anyone gonna look into this problem? Meeting with the same issue

**Comment by wuzinong** [comment]
@oelbaganwg  Any solution or work around ?

**Comment by skaltenegger** [comment]
@oelbaganwg @wuzinong did you take a look at issue #273 - I just commented there...

**Comment by MMT-LD** [comment]
@skaltenegger i use rollup? how would one accomplish this? For now i reverted back to older version until i can get this working in ie11.

Thanks in advance.

**Comment by kidjp85** [comment]
Hi @oelbaganwg , does this show any error ? And which version of 'react-id-swiper' are u using ?

**Comment by oelbaganwg** [comment]
I think the issue may be unrelated, because I tried using react id swiper on a clean project without any other plugins and it worked on IE. I still can't pinpoint where the clash would be with other plugins.

**Comment by kidjp85** [comment]
There is another option I think you guys can try is building your own Swiper locally by changing Gulp config in Swiper's package and put it in your code base.  More detail [here](https://swiperjs.com/api/#custom-build)
