### ISSUE TITLE
Unexpected token: name «Dom7», expected: punc «;»

### ISSUE THREAD

**Issue by codeSnipe** [kidjp85/react-id-swiper#324]
when I build the project, the error is appeard. 
I only use  the component with the normal config.

**Comment by codeSnipe** [comment]
js/3.bundle.js from UglifyJs

When the project build with UglifyJs, Unexpected token

**Comment by kaankucukx** [comment]
@codeSnipe Same here! project unable to compile with UglifyJs.

If you remove uglifyjs from webpack config. Then compilation works but other issues occur.

**Comment by tohbansoon** [comment]
any updates on this issues???

**Comment by kaankucukx** [comment]
I fixed this with switching [UglifyJS](https://webpack.js.org/plugins/uglifyjs-webpack-plugin/) with [TerserPlugin](https://webpack.js.org/plugins/terser-webpack-plugin/)

Below is my options.

```javascript
optimization: {
    minimizer: [
      new TerserPlugin({
        parallel: true,
        cache: true,
        extractComments: true,
        terserOptions: {
          ecma: 5,
          ie8: false,
          compress: true,
          warnings: true,
        },
      }),
    ],```

**Comment by lhtdesignde** [comment]
I ran into this issue. Is switching to terser the only way? Currently I'm trying to exclude the folder but it seems not to work.

**Comment by lhtdesignde** [comment]
Ok nevermind. Here is the explanation: https://github.com/mishoo/UglifyJS2/issues/659#issuecomment-447820525

**Comment by fishme** [comment]
right the solution with switching is just a cheep workaround.

**Comment by lhtdesignde** [comment]
Yes, i ended up staying with uglify and running dom7 and swiper through babel first. I kinda like that it breaks because it warns me for errors that otherwise we would only see after building when testing IE.
