### ISSUE TITLE
Swiper update method

### ISSUE THREAD

**Issue by denny7** [kidjp85/react-id-swiper#326]
Hello! I'm using SSR and I want to update Swiper's size when componentDidMount. It seems methods `update` and `updateSize` are not supported any more. I updated to 2.3.2 and get swiper instance by adding `getSwiper: this.updateSwiper` in props. When I resize the width and get well. How can I achieve that without need to resize?

**Comment by goriverna** [comment]
Any news about that ?

**Comment by goriverna** [comment]
I added in params this field:
```
{
      shouldSwiperUpdate:true,
      rebuildOnUpdate:true,
}
```
Now it work always and you don't have to resize o force update
