### ISSUE TITLE
Not working in ie11 

### ISSUE THREAD

**Issue by MMT-LD** [kidjp85/react-id-swiper#332]
https://github.com/kidjp85/react-id-swiper/issues/273 - same issue as the closed post - kind of addresses the issue for webpack people but has anyone any idea how to get this to work with rollup? I have had to revert to an older version to get this working in ie11 😒

**Comment by kidjp85** [comment]
Hi @MMT-LD , which version of React-id-swiper are you using ? And how did you import the js file ?

**Comment by Antonio-Laguna** [comment]
Issue here is https://github.com/nolimits4web/swiper/issues/3073

**Comment by MMT-LD** [comment]
> Hi @MMT-LD , which version of React-id-swiper are you using ? And how did you import the js file ?

exactly like @firstandthird describes

**Comment by Antonio-Laguna** [comment]
I wonder @kidjp85 if you could export a version that imports the transpiled version of Swiper instead just so others can choose. As of right now, there's no fix except for tweaking the webpack config which is not always a possibility.

**Comment by MMT-LD** [comment]
> I wonder @kidjp85 if you could export a version that imports the transpiled version of Swiper instead just so others can choose. As of right now, there's no fix except for tweaking the webpack config which is not always a possibility.

Agree, however not sure that will solve the issue

**Comment by Antonio-Laguna** [comment]
Won't solve the issue itself but it doesn't seem like Swiper wants to. However it does give react-id-swiper consumers an option to circumvent that.

**Comment by MMT-LD** [comment]
> Won't solve the issue itself but it doesn't seem like Swiper wants to. However it does give react-id-swiper consumers an option to circumvent that.

i see where your going with this 😄

**Comment by MMT-LD** [comment]
Any update on this... would really appreciate being able to upgrade.... ;-)

**Comment by tohbansoon** [comment]
Hi guys, any findings to resolve this?? 
According to react-id-swiper document, I have added this into the webpack.config.js. I believe this is to use babel to transpile the code into es5
```
{
    test: /\.js(x)?$/,
    exclude: [/node_modules\/(?!(swiper|dom7)\/).*/, /\.test\.jsx?$/],
    use: [{ loader: 'babel-loader' }],
},
```

But after npm run build, I can still find `const` syntax inside the .js file in dist folder... 

This cause old browser like safari9 or IE10 display error as below
```
SyntaxError: Use of const in strict mode.
```

**Comment by RyanGosden** [comment]
Ive also hit the same wall. Tried including the swiper and dom7 modules to be transpiled but that did not work. Would be great if we could import swiper lib independently

**Comment by jwilson114** [comment]
"Ensure your babel config file is programmatically created (babel.config.js and not a .babelrc file)." solved it for me! Thanks

**Comment by kidjp85** [comment]
There is another option I think you guys can try is building your own Swiper locally by changing Gulp config in Swiper's package and put it in your code base.  More detail [here](https://swiperjs.com/api/#custom-build)

**Comment by DenisSemionov** [comment]
@RyanGosden , thanks, that actually helped.

**Comment by 224137748** [comment]
The swiper library has three entrances: Main, Module, and jsNext: Main.  But 'react-id-swiper' lib use the 'module-entry' default.
```
{
  "name": "swiper",
  "version": "5.4.5",
  "description": "Most modern mobile touch slider and framework with hardware accelerated transitions",
  "main": "js/swiper.js",
  "jsnext:main": "js/swiper.esm.bundle.js",
  "module": "js/swiper.esm.bundle.js",
  "scripts": {
    "postinstall": "echo \"\u001b[35m\u001b[1mLove Swiper? Support Vladimir's work by donating or pledging on patreon:\u001b[22m\u001b[39m\n > \u001b[32mhttps://patreon.com/vladimirkharlampidi\u001b[0m\n\""
  },
......
}
```

This can be fixed by setting the import package entry file to main in the WebPack configuration file.

```
webpack.config = {
  // .....
  resolve: {
    mainFields: ['main', 'browser', 'module'];
  }
  // .....
}```
