### ISSUE TITLE
Cannot track activeIndex in state or even in parents state

### ISSUE THREAD

**Issue by N00nDay** [kidjp85/react-id-swiper#335]
Anytime I attempt to track the active index in state or the parents state I get the following error:

`Uncaught TypeError: Cannot read property 'swiper' of undefined`

Are there any examples of how to make this work because if this doesn't I don't see how this plugin is usable outside of simply viewing images and thats it.  I need to be able to use methods for which image I am viewing, ie delete, favorite, share, etc.  I have figured out all of them except the favorite method and this is because in order to show whether the active slide is already favorited I need to relay the active Index to the parent container.  Seems like it shoul be pretty straight forward but not the case.

**Comment by kidjp85** [comment]
Hi @N00nDay , you can find the example from Codesanbox demo.
