### ISSUE TITLE
How can i get the swiper instance outside of the component?

### ISSUE THREAD

**Issue by rollawaypoint** [kidjp85/react-id-swiper#337]
I want to use the methods of instance outside of the component, but it seems no way to get the swiper instance in documentation and examples.

issue #20 didn't work for me, init has no argument of swiper

react-id-swiper version: 2.3.2

**Comment by rollawaypoint** [comment]
I had found the getSwiper method in ReactIdSwiper.tsx.
so i closed the issue.

**Comment by demon-zhonglin** [comment]
> I had found the getSwiper method in ReactIdSwiper.tsx.
> so i closed the issue.

May I ask how to deal with getSwiper?

**Comment by alexandprivate** [comment]
A simple solution to this:
`const [swiper, setSwiper] = React.useState(null);

  let goNext = () => swiper.slideNext();

  let goPrev = () => {swiper.slidePrev();

React.useEffect(() => {
    var mySwiper = document.querySelector(".swiper-container").swiper;
    setSwiper(mySwiper);
  }, [swiper]);

<button
        className="swiper-nav-button-custom swiper-button-prev-custom"
        onClick={goPrev}
      />
      <button
        className="swiper-nav-button-custom swiper-button-next-custom"
        onClick={goNext}
      />`
