### ISSUE TITLE
Set height on container with containerStyle (or similar)

### ISSUE THREAD

**Issue by marwej** [kidjp85/react-id-swiper#340]
With Swiper 5.0 the container needs a fixed height. Would it be possible to add a prop `containerStyle` which you then could use to pass this height?

**Comment by AlanMauricioC** [comment]
Hi i actually found in the docs containerClass, maybe is what are you searching for
[https://react-id-swiper.ashernguyen.site/doc/api](url)

**Comment by marwej** [comment]
In my application the height could vary, and I must pass a number (the height). I guess it could be done in other ways too, but not as nice as this.

**Comment by gitygity** [comment]
I have same problem :(

**Comment by kidjp85** [comment]
I think you just need to override the container style from the stylesheet.

**Comment by marwej** [comment]
Yes, but inline styles is a more elegant solution. :)
