### ISSUE TITLE
slideChange Event in Class Component

### ISSUE THREAD

**Issue by mathishuettl** [kidjp85/react-id-swiper#341]
hello,

how can I get the slideIndex from the slideChange event? I am unsing react with React.Component class and I can't find any solution.

```
class myComponent extends React.Component {
    onSlideChange(x) {
        console.log(x);
    }

    render(
        const params = {Swiper, on: { slideChange: this.onSlideChange } }

        <Swiper {...params}></Swiper>
    );
}
```

**Comment by kidjp85** [comment]
Hi @mathishuettl , you should add event after Swiper instance is created. You can find the sample code from Codesanbox demo
