### ISSUE TITLE
ie11 next.config.js

### ISSUE THREAD

**Issue by Powza** [kidjp85/react-id-swiper#343]
What's the best way to implement ie11 support with next.js?

I tried using the Webpack example but can't figure out how to make that work with next.js webpack config.
```javascript
const webpack = require("webpack");
module.exports = {
  webpack: (config, { defaultLoaders }) => {
    config.module.rules.push({
      exclude: [/node_modules\/(?!(swiper|dom7)\/).*/, /\.test\.js(x)?$/],
      test: /\.js(x)?$/,
      use: defaultLoaders.babel
    });
    return config;
  }
};
```

**Comment by kidjp85** [comment]
You can find more info [here](https://github.com/kidjp85/react-id-swiper/issues/259)
