### ISSUE TITLE
Uncaught TypeError: react_1.useRef is not a function

### ISSUE THREAD

**Issue by alexeenko-frontend** [kidjp85/react-id-swiper#346]
Slider is loaded and then throws an error.

react-dom version
`"react-dom": "^16.8.6"`

```
import Swiper from "react-id-swiper";

...

<Swiper>
  <div>1</div>
  <div>2</div>
  <div>3</div>
</Swiper>
```

**Comment by aktywnitu** [comment]
How did you solve the problem?

**Comment by alexeenko-frontend** [comment]
I deleted node_modules folder, then executed "npm i".

пн, 2 дек. 2019 г. в 13:20, aktywnitu <notifications@github.com>:
