### ISSUE TITLE
 Could not find a declaration file for module 'swiper'.

### ISSUE THREAD

**Issue by fxOne** [kidjp85/react-id-swiper#348]
I'm getting the following error if I follow the installation guide:

```
 Could not find a declaration file for module 'swiper'. '/var/octaved/dev/hcontent/node_modules/swiper/js/swiper.js' implicitly has an 'any' type.
  Try `npm install @types/swiper` if it exists or add a new declaration (.d.ts) file containing `declare module 'swiper';`

2 import Swiper, { SwiperOptions, SelectableElement, SwiperModule } from 'swiper';
```

I could easily solve this issue by installing the `@types/swiper`, but it would be better if this is mentioned in the installation guide and adding `@types/swiper` to the `peerDependencies`.

**Comment by kidjp85** [comment]
I don't want to add to `peerDependencies` because many developers are not using typescript. Thank you for the advance, I will mention this in the doc

**Comment by from-nobody** [comment]
add "declare module 'swiper/*';" in "env.d.ts" file

**Comment by Khaan25** [comment]
I did npm i swiper@latest and it worked. I was trying to integrate Autoplay but it could not find the modules

`import { Autoplay, Navigation } from 'swiper/modules'`

This line was giving me error

**Comment by yenche123** [comment]
> I did npm i swiper@latest and it worked. I was trying to integrate Autoplay but it could not find the modules
> 
> `import { Autoplay, Navigation } from 'swiper/modules'`
> 
> This line was giving me error

Me too @Khaan25 

<img width="398" alt="image" src="https://github.com/kidjp85/react-id-swiper/assets/28533125/19a7e245-ff5d-4e21-994c-becc7193cbaa">

**Comment by yenche123** [comment]
@Khaan25 I found that directly importing from `swiper` instead of `swiper/modules` can resolve the issue, like this:

```ts
import { Autoplay, Navigation } from 'swiper'
```

**Comment by yenche123** [comment]
well well well, I found that the above line is supported by `v9`
When I upgrade to `v10`, it exactly is:
```ts
import { Autoplay, Navigation } from 'swiper/modules'
```
So I think we need to check out our `package.json` to decide which version we shoud use.

**Comment by Khaan25** [comment]
If you are using typscript, we need to declare inside global.d.ts 
declare 'swiper';

and it fixes that but in this case, it worked. I also installed the types of that.
