### ISSUE TITLE
Update to latest swiper 5.1.0 version

### ISSUE THREAD

**Issue by groomain** [kidjp85/react-id-swiper#349]
Is it possible to update the package to the latest version of swiper. 
@kidjp85 🙏

**Comment by lhtdesignde** [comment]
please 5.1.0 now since it fixes errors with ios 13

**Comment by fxOne** [comment]
As by [documentation](https://github.com/kidjp85/react-id-swiper#npm-package) you install the latest version of swiper yourself `npm install --save react-id-swiper@latest swiper@latest`. 

If there are any errors with the latest `swiper` version maybe you should post the error here.

**Comment by kidjp85** [comment]
Hi @groomain , sorry for the late response. I will try my best to update new version within this week.

**Comment by kidjp85** [comment]
Newest version was released!
