### ISSUE TITLE
prev and back buttons not changing the slide

### ISSUE THREAD

**Issue by simran-k** [kidjp85/react-id-swiper#35]
Slides change on autoplay and with pagination click but forward and back button do not work at all.

```
 <div id="homePageSlider">
                          <Swiper>
                                 <img alt="sweats-cards" classname="lazyload banner_main" name="sweats-cards-9-12-16" src=xyz.jpg" />
                          </Swiper>
                        </div>
                      </div>

```

I have tried passing this   const params = {
        pagination: '.swiper-pagination',
        nextButton: '.swiper-button-next',
        prevButton: '.swiper-button-prev',
        paginationClickable: true,
        spaceBetween: 30,
        centeredSlides: true
      };

as well but no luck

**Comment by kidjp85** [comment]
Hi @simran-k , thank you for your report. I checked your example code , do you have only one item in your slider ?
