### ISSUE TITLE
getSwiper hook causes render loop with rebuildOnUpdate

### ISSUE THREAD

**Issue by Awem** [kidjp85/react-id-swiper#351]
Steps to reproduce:

- go to the `getSwiper` hook demo: https://codesandbox.io/s/reactidswiper-demo-w86n9
- add this to params:
```
   rebuildOnUpdate: true,
   on: {
      init() {
        console.error("init");
      }
    }
```

expected  behaviour:
`init` is only called a few times

actual behaviour:
`init` is called in an infinite render loop

**Comment by kidjp85** [comment]
It's causing a loop there not because `getSwiper`. You did put `rebuildOnUpdate` on params that made `Swiper` recreated all the time.

**Comment by Awem** [comment]
Not sure what you mean. Yes, it caused by `rebuildOnUpdate`, but only in conjunction with `getSwiper`. So do you suggest that `rebuildOnUpdate` should not be included in params? What would be the correct way to use the `rebuildOnUpdate` together with `getSwiper` then?
Actually I just found that this is a duplicate of https://github.com/kidjp85/react-id-swiper/issues/327
