### ISSUE TITLE
getSwiper error in the Thumbs Gallery example

### ISSUE THREAD

**Issue by beautycss** [kidjp85/react-id-swiper#352]
After tried the [thumb example](https://react-id-swiper.ashernguyen.site/example/thumbs-gallery-with-two-way-control) and see this [issue](https://github.com/kidjp85/react-id-swiper/issues/297).

I find the "getSwiper: thumbnailSwiper," should be "getSwiper: getThumbnailSwiper," in the [thumb example](https://react-id-swiper.ashernguyen.site/example/thumbs-gallery-with-two-way-control), or the thumbnailSwiper don't slide with the gallerySwiper.

**Comment by kidjp85** [comment]
Hi @beautycss , thank you for the notice. I updated new doc on demo page
