### ISSUE TITLE
2.4.0 Version should be 3.0.0

### ISSUE THREAD

**Issue by cmaerz** [kidjp85/react-id-swiper#363]
The removal of the `node_modules/react-id-swiper/lib/styles/scss/swiper` File breaks current deployments if an `@import` to this file was used. 
So either you should release a 2.4.1 Version where this file still exists and just imports the swiper scss file or push the Version to 3.0.0 and remove the 2.4.0 Version.

**Comment by mawburn** [comment]
This is breaking out builds and is kind of annoying. A breaking change shouldn't be automatically updated. Locking it down to `v2.3.2` fixes the issue for us.

**Comment by AlexReff** [comment]
The documentation is also not updated, I had to come to this issue to figure out what to do. Please use semantic versioning. Is this repo even being maintained?
