### ISSUE TITLE
Breakpoints don't pick up noSwiping

### ISSUE THREAD

**Issue by neighlyd-alo** [kidjp85/react-id-swiper#367]
Hello,

Great library! Thanks so much!

I have a carousel that displays differently using the `breakpoints` object. However, the `noSwiping: bool` within the `breakpoints` objects is not being picked up. `noSwiping` will only register if it is placed at the root of the object.

Works (though noSwiping is set for all breakpoints):
```
const config = {
  centeredSlides: true,
  noSwiping: true,
  rebuildOnUpdate: true,
  slidesPerView: 1.2,
  spaceBetween: 16,
  breakpoints: {
    [breakpoints[0]]: {
      slidesPerView: 1.5,
      spacebetween: 16
    },
    [breakpoints[1]]: {
      slidesPerView: 3,
      spaceBetween: 26,
      centeredSlides: false
    }
  }
}
```

Doesn't work (for any breakpoints):

```
const config = {
  centeredSlides: true,
  rebuildOnUpdate: true,
  slidesPerView: 1.2,
  spaceBetween: 16,
  breakpoints: {
    [breakpoints[0]]: {
      slidesPerView: 1.5,
      spacebetween: 16,
      noSwiping: false,
    },
    [breakpoints[1]]: {
      slidesPerView: 3,
      spaceBetween: 26,
      centeredSlides: false,
      noSwiping: true
    }
  }
}
```

Is this a known issue or is there any way around it?

**Comment by neighlyd-alo** [comment]
I just realized that I was dealing with inheritance from breakpoints, my bad!

**Comment by alekslario** [comment]
Why is this issue closed? I have the same problem...
