### ISSUE TITLE
next set of slides never becomes visible

### ISSUE THREAD

**Issue by simran-k** [kidjp85/react-id-swiper#37]
I am passing these parameters:

 const params = {
    pagination: '.swiper-pagination',
    slidesPerView: 2,
    paginationClickable: true,
    spaceBetween: 30
  };

I have 12 slides in the slider. It only shows as many slides as I mention in slides per view and scrolling to right never gives more elements no matter I pass 3 or 6 or 1

looks like this with 2 slides per view. next set of slides never appears

![iisuegit](https://cloud.githubusercontent.com/assets/17847555/21893318/a042137a-d900-11e6-8ec6-64530d53161c.png)

**Comment by kidjp85** [comment]
Hi @simran-k , thank you for your report. Can u give me more detailed info like
- Which version of React-id-swiper are u using now ?
- Are u using built in stylesheet ?
- It would be more helpful if u can put the source code of ur slider component here ?

Thanks
