### ISSUE TITLE
how can i get swiper‘s id after i swipered

### ISSUE THREAD

**Issue by Sallywa** [kidjp85/react-id-swiper#372]
i am now writing a topbar。its style changes corresponding to the swiper id but i can't get  swiper id after i swipered，is there a way ？

**Comment by ixuxinyue** [comment]
Hi. I met the same problem. Do you know the way to get the index of current page when swipering now?

**Comment by HoangNguyen-0701** [comment]
Hi. I met the same problem too !

**Comment by NilapuAnusha** [comment]
@kidjp85 How to get current active slide/page id after swiping?

**Comment by jere-co** [comment]
```Javascript
  useEffect(() => {
    if (swiper !== null) {
      console.log(swiper.activeIndex);
    }
  });
```

**Comment by kidjp85** [comment]
@NilapuAnusha I think you can find it from the doc or Live demo in Codesanbox
