### ISSUE TITLE
Possible to sync two swipers?

### ISSUE THREAD

**Issue by goellner** [kidjp85/react-id-swiper#378]
I want to have two swipers side by side with one control on the outside (that works thanks to the thumb gallery example).

My question is, is it possible to also sync the dragging between the two? When dragging the left swiper, it should mirror that drag to the right swiper.

Any help appreciated

**Comment by goellner** [comment]
nvm. didn't see the useEffect in there. going to get my eyes checked now

**Comment by dsfrederic** [comment]
@goellner how did you manage to solve this?

**Comment by goellner** [comment]
@dsfrederic I solved it by setting up the same as in the the Thumbs gallery with two-way control here: https://react-id-swiper.ashernguyen.site/example/thumbs-gallery-with-two-way-control
