### ISSUE TITLE
Issue with multiple slides per view

### ISSUE THREAD

**Issue by yogeshbv** [kidjp85/react-id-swiper#387]
I am using version 1.6.9 just because my project is using react 15 version. When I am using multiple-slides-per-view with slidesPerView: 4, its showing single slide.
![image](https://user-images.githubusercontent.com/8022566/73645654-b218c900-469d-11ea-821f-b66c95cda25d.png)

But after some seconds it shows multi item slider:-
![image](https://user-images.githubusercontent.com/8022566/73645989-79c5ba80-469e-11ea-95b9-c20083e5aa03.png)

How can I solve this?

**Comment by meljoum** [comment]
I have the same issue any solution plz?

**Comment by meljoum** [comment]
Finally, i fixed the issue, look at this #185,  just make sure the length of the array of items is bigger than 0

**Comment by FazilaMehtab** [comment]
Have you solve this issue?? I am having same error please help and its not solving by check length of array I am already doing it.

    { books && books.length > 0 &&(

      <Swiper {...params} ref={swiperRef} shouldSwiperUpdate rebuildOnUpdate> 
          { books.length>0 && books.map((book: TBook) => (
            <div key={book._id} className="customdiv">
              <img src={book.img} className="customImg" />
            </div>
          ))
     </Swiper>
    )}

thanks
