### ISSUE TITLE
Link to stylesheet file from CDN doesn't work

### ISSUE THREAD

**Issue by fox-tracks** [kidjp85/react-id-swiper#397]
I try to open link to Swiper stylesheet file from your package description https://cdnjs.cloudflare.com/ajax/libs/Swiper/5.2.0/css/swiper.css
or 
https://cdnjs.cloudflare.com/ajax/libs/Swiper/5.2.0/css/swiper.min.css
and receive 404 Error

**Comment by kidjp85** [comment]
It should be fixed with the newest release
