### ISSUE TITLE
Wrong slides width

### ISSUE THREAD

**Issue by Crysp** [kidjp85/react-id-swiper#401]
Hi 👋

If there are no children on first render, second render returns slides with wrong width.

I could wrap swiper component into array length checking condition but i think this is not right behaviour

Here is an example:

https://codesandbox.io/s/swiper-issue-46n1e

**Comment by Natteke** [comment]
Same issue

**Comment by guilhermebpereira** [comment]
following documentation, you should call .update() whenever you add/remove slides from swiper.
I fixed your example to demonstrate it working: https://codesandbox.io/s/swiper-issue-duwb8

**Comment by Crysp** [comment]
I think this is still uncomfortable way to use slider

What if we add `children` as effect dependency? At first look it's fixing my issue
https://github.com/kidjp85/react-id-swiper/blob/e13cace73e55886a635f26535d57d47c31a9df1c/src/ReactIdSwiper.tsx#L125-L135

**Comment by guilhermebpereira** [comment]
I think the way it is today, it looks natural and makes sense. Perhaps your suggestion makes sense too. I think you should submit a PR and see what people think about it 😃

**Comment by Natteke** [comment]
> I think this is still uncomfortable way to use slider
> 
> What if we add `children` as effect dependency? At first look it's fixing my issue
> https://github.com/kidjp85/react-id-swiper/blob/e13cace73e55886a635f26535d57d47c31a9df1c/src/ReactIdSwiper.tsx#L125-L135

At least now i can make it works as i need, thanks!

**Comment by kidjp85** [comment]
@Crysp , this topic has been discussed many times. It's highly recommended to return `null` if swiper's children are empty.
