### ISSUE TITLE
Can't scroll vertically on the swiper area iOS.

### ISSUE THREAD

**Issue by heekodev** [kidjp85/react-id-swiper#405]
I have a swiper with horizontal scroll inside a modal which has a vertical scroll since its height is greater than the length. But it is not scrollable on iOS when trying to scroll from the swiper area. scrolling works fine in the rest of the modal. and in web and android also works fine, but in iPhone cant scroll vertically from the swiper area.

**Comment by olso** [comment]
@heekodev did you manage to fix it?

```jsx
touchReleaseOnEdges
        threshold={5}
        mousewheel={false}
```
