### ISSUE TITLE
last slides (1-2) in container with slidesPerView: 'auto' sometimes not visible

### ISSUE THREAD

**Issue by NqCompiler** [kidjp85/react-id-swiper#406]
Hi,

Thanks for the great work.
I have an application where I use the following Properties for the Swiper component.
```
{
          direction: 'horizontal',
          loop: false,
          containerClass: 'swiper-container',
          slidesPerView: 'auto'
}
```

sometimes the last 1 or 2 slides are not visible and when I try to swipe to them I can see them but if I let go it always swipes back to the last slide that is visible. I tried multiple update mechanisms but the bug seems to be there. It's hard to reproduce because it happens randomly. 

Do you have any idea why this is happening and how I can reproduce it better?

**Comment by hendaoui** [comment]
did you find a solution ?

**Comment by NqCompiler** [comment]
I did not, but today I opened an issue at the nolimits4web/swiper repo, maybe they can help me with it.
I'll keep this issue updated.
This is the issue: https://github.com/nolimits4web/swiper/issues/3611

**Comment by NqCompiler** [comment]
solution: https://github.com/nolimits4web/swiper/issues/3611#issuecomment-671983101
Hope it helps!
