### ISSUE TITLE
example customized-component code params is miss, remind you can make up

### ISSUE THREAD

**Issue by imagine10255** [kidjp85/react-id-swiper#412]
Hi, example code params is miss, remind you can make up

https://react-id-swiper.ashernguyen.site/example/customized-component

```js
...
renderSrollbar: () => <CustomScrollbar><hr/></CustomScrollbar>
// renderScrollbar (miss 'c')
```

**Comment by kidjp85** [comment]
Hi @imagine10255 , you can check the available [live example](https://codesandbox.io/s/customized-component-example-nksc2) for this in Codesandbox
