### ISSUE TITLE
renderPagination, Button, Scrollbar move out <ContainerEl>

### ISSUE THREAD

**Issue by imagine10255** [kidjp85/react-id-swiper#413]
Hi, May I ask if the paging and navigation control can be moved out of `<ContainerEl>`, because the `overflow: hidden` of `<ContainerEl>` will make it impossible to move the paging or navigation control out of the body, and it will become necessary to handle paging and navigation control by getSwiper.
But it can actually be done faster with `renderPagination(), renderScrollbar(), renderNextButton(), renderPrevButton ()`

in https://github.com/kidjp85/react-id-swiper/blob/master/src/ReactIdSwiper.tsx#L180-L183

move out <ContainerEl>
```js
{pagination && pagination.el && renderPagination && renderPagination(props)}
{scrollbar && scrollbar.el && renderScrollbar && renderScrollbar(props)}
{navigation && navigation.nextEl && renderNextButton && renderNextButton(props)}
{navigation && navigation.prevEl && renderPrevButton && renderPrevButton(props)}
```

proposed changes
```js
<div>
    <ContainerEl className={containerClass} dir={rtl && 'rtl'} ref={swiperNodeRef}>
          {parallax && parallaxEl && renderParallax && renderParallax(props)}
          <WrapperEl className={wrapperClass}>{Children.map(children, renderContent)}</WrapperEl>
    </ContainerEl>

      {pagination && pagination.el && renderPagination && renderPagination(props)}
      {scrollbar && scrollbar.el && renderScrollbar && renderScrollbar(props)}
      {navigation && navigation.nextEl && renderNextButton && renderNextButton(props)}
      {navigation && navigation.prevEl && renderPrevButton && renderPrevButton(props)}
</div>
```

example
![image](https://user-images.githubusercontent.com/5771353/77238668-5edae580-6c0d-11ea-838c-666d7713bf81.png)

**Comment by kkashou** [comment]
Any update on this?

**Comment by kidjp85** [comment]
With the newest version, `getSwiper` has been deprecated. Now you can use `ref` to control Swiper instance from outside

**Comment by imagine10255** [comment]
@kidjp85 Hi, I mean, there was a way to render navigation buttons, but the position of the structure is awkward, it will be affected by overflow, and it has nothing to do with getSwiper
