### ISSUE TITLE
Update of styles documentation on website

### ISSUE THREAD

**Issue by tekyu** [kidjp85/react-id-swiper#418]
Website does not provide correct information (as it doesn't mention version) of styles of the swiper.
![image](https://user-images.githubusercontent.com/17339869/78459657-ef5c0000-76ba-11ea-9094-06860df1853a.png)

While on github readme it states
![image](https://user-images.githubusercontent.com/17339869/78459667-fe42b280-76ba-11ea-8cff-d2beb823a546.png)

I've been really scratching my head why there is no styles under this path

**Comment by kidjp85** [comment]
I will try my best to deploy the documentation website very soon.
