### ISSUE TITLE
noSwiping parameter doesn't change on breakpoints

### ISSUE THREAD

**Issue by patibugaj** [kidjp85/react-id-swiper#420]
I found an issue, that `noSwiping` parameter set in the root of the settings works correctly. But when I try to change it in a breakpoint, there is no effect.

My code:
```
const settings = {
    autoHeight: true,
    speed: 100,
    slidesPerView: 1.5,
    noSwiping: true,
    getSwiper: updateSwiper, // Get swiper instance callback
    breakpoints: {
      1280: {
        slidesPerView: 5
      },
      960: {
        slidesPerView: 4
      },
      768: {
        noSwiping: false,
        slidesPerView: 3,
        loop: true
      },
      576: {
        noSwiping: false,
        slidesPerView: 2,
        centeredSlides: true,
        loop: true
      }
    }
```

**Comment by patibugaj** [comment]
I've found out that adding 'swiper-no-swiping' class name to the element and removing it depends on the breakpoint works. But still, I don't understand why the `noSwiping` parameter doesn't work.

**Comment by nathany** [comment]
I transitioned to a full vertical list on mobile. It is having issues with scrolling which is remedied with `noSwiping`. I still want swiping on desktop though, so supporting it in a breakpoint would be useful.

**Comment by nathany** [comment]
This appears to work:

```
noSwiping: true,
    breakpoints: {
      320: {
        direction: 'vertical',
        slidesPerView: 'auto',
      },
      992: {
        direction: 'horizontal',
        slidesPerView: 4,
        noSwiping: false,
      },
    },
```

**Comment by kidjp85** [comment]
`noSwiping` is `react-id-swiper`'s config param. It won't work  with `breakpoints` config which is belonged to `Swiper`
