### ISSUE TITLE
Infinite render loop

### ISSUE THREAD

**Issue by thebiltheory** [kidjp85/react-id-swiper#422]
## Current Behavior
`getSwiper` is causing an infinite render loop.

## Steps to Reproduce
```javascript
const [swiper, setSwiper] = useState()
return (
    <Swiper {...params} getSwiper={setSwiper}>
        {children}
    </Swiper>
)
```
Does anyone found a solution for this?

**Comment by kidjp85** [comment]
This issue was fixed since 3.x. From 4.x, `getSwiper` is deprecated.
