### ISSUE TITLE
Autoplay in demo isn't working?

### ISSUE THREAD

**Issue by kkashou** [kidjp85/react-id-swiper#423]
Hello,

In the demo https://react-id-swiper.ashernguyen.site/example/auto-play the autoplay doesn't stop when i hover over the slider. It still continues to play. Am I missing something?

**Comment by pimdewit** [comment]
It doesn't provide that functionality in the original Swiper library either (https://swiperjs.com/demos/#autoplay)
Maybe you could call `swiper.autoplay.stop()` on pointerover?

**Comment by kkashou** [comment]
@pimdewit i ended up doing a hover check in react and autoplay stop and then off of it autoplay start. So did it that way instead.
