### ISSUE TITLE
There is something wrong in the document.

### ISSUE THREAD

**Issue by wy1009** [kidjp85/react-id-swiper#424]
https://react-id-swiper.ashernguyen.site/example/custom-pagination

```
renderBullet: (index, className) => {
  return '<span className="' + className + '">' + (index + 1) + '</span>';
}
```

It should be:

```
renderBullet: (index, className) => {
  return '<span class="' + className + '">' + (index + 1) + '</span>';
}
```

or it won't work.

It took me half an hour to find out this. TAT

**Comment by kidjp85** [comment]
My mistake. Will update this when releasing new version for doc website

**Comment by wy1009** [comment]
> My mistake. Will update this when releasing new version for doc website

Thank you so much~

**Comment by suomao01** [comment]
我有一个问题，关于keepAlive的用法，我这里怎么都不生效，可否协助，拜谢
