### ISSUE TITLE
style dosnt load cause it dosnt exist in node_modules ?

### ISSUE THREAD

**Issue by Astanusic** [kidjp85/react-id-swiper#445]
Hi,

After my "yarn add blablabla" the console says it cant find the scss or css file.

I manually checked if the file was existing but it's not.

**Comment by Astanusic** [comment]
Im closing it myself, the problem is that the website with the documentation is NOT UP TO DATE.
If anyone see this, just read doc from this repo only.

**Comment by jDeppen** [comment]
https://github.com/kidjp85/react-id-swiper#styling
