### ISSUE TITLE
Problem with pagination rendering

### ISSUE THREAD

**Issue by aimarjs** [kidjp85/react-id-swiper#45]
Hi! 

I have issue with rendering pagination bullets. As soon as i refresh my page, only one swiper pagination bullet will appear. If i resize the screen just a bit, all bullets will come back. 
I'm stuck a bit. Maybe you can help? 

Check the gif, please.

![why](https://cloud.githubusercontent.com/assets/25065245/23585982/3c4b6be6-018c-11e7-972c-15dee918aa67.gif)

**Comment by qbeauperin** [comment]
I have a similar issue.
When loading the page for the first time, I can drag the first slide but it won't go the the next one and ignore any given parameter ("centeredSlides", "slidesPerView", "spaceBetween"...) , but as soon as I resize the screen (even juste one pixel), everything works fine.

**Comment by kidjp85** [comment]
Hi @aimarjs , it will be really helpful if u can share ur code :)
