### ISSUE TITLE
Gatsby + Autoplay

### ISSUE THREAD

**Issue by mister-cairns** [kidjp85/react-id-swiper#469]
I'm unable to get the Autoplay feature working in Gatsby. Looking through the issues, it looks like I have to include it as a module, but `import { Autoplay } from "swiper/dist/js/swiper.esm";` throws an error. My current params are below, which is based on the current docs:

```
 const sliderParams = {
    direction: 'vertical',
    slidesPerView: 1,
    loop: true,
    centeredSlides: true,
    autoHeight: true,
    autoplay: {
      delay: 2500,
      disableOnInteraction: false
    },
  }
```

**Comment by jxwolstenholme** [comment]
Also having an issue here. Nothing I do seems to get the autoplay feature to work.

**Comment by anguy95** [comment]
@mister-cairns 
Not sure if you are still having this issue but doing this worked for me. 

`import { Autoplay, Swiper as RealSwiper } from 'swiper';`

Then inside the component call: 

`RealSwiper.use(Autoplay);`

Hope this helps.

**Comment by G9000** [comment]
try to use this https://swiperjs.com/react

import SwiperCore, { Autoplay } from "swiper/core"

SwiperCore.use([Autoplay])
