### ISSUE TITLE
problems on "Backend"

### ISSUE THREAD

**Issue by crazyx13th** [kidjp85/react-id-swiper#48]
Hi there!

I have a problem on React at the server side... I got ReferenceError: navigator is not defined
    at D:\workspace\travelcoup-web-ui\node_modules\swiper\dist\js\swiper.js:4443:42

Some Ideas for a fix?

Thx! Great Job!

Cya crazyx13th

**Comment by crazyx13th** [comment]
a first workaround:
`module.exports = factory(
      require('react'),
      require('react-dom'), 
        !!((typeof window !== 'undefined' && window.document && window.document.createElement)) ? require('swiper'): null,
      require('object-assign')
    );`

**Comment by kidjp85** [comment]
Hi @crazyx13th , here is a solution we already discussed https://github.com/kidjp85/react-id-swiper/issues/14 .

**Comment by AlecRust** [comment]
@kidjp85 if the main Swiper works fine with React (https://github.com/nolimits4web/Swiper/issues/1541#issuecomment-279026950) does react-id-swiper offer any benefits?

**Comment by halt-hammerzeit** [comment]
For whoever googling this: `Swiper` library seems to be lame not supporting server-side at all.
Still there is a hacky workaround: https://github.com/nolimits4web/Swiper/issues/1541#issuecomment-271439046

**Comment by halt-hammerzeit** [comment]
`<Swiper>` original component can be wrapped to fix it for the server side:

```js
import React, { Component } from 'react'

// https://github.com/nolimits4web/Swiper/issues/1541#issuecomment-271439046
export default class FixedSlider extends Component {
  state = {}

  componentDidMount() {
    this.setState({
      Swiper: require('react-id-swiper')
    })
  }

  render() {
    const { Swiper } = this.state

    if (!Swiper) {
      return null
    }

    return <Swiper {...this.props}>{this.props.children}</Swiper>
  }
}
```
