### ISSUE TITLE
Unhandled Runtime Error  RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by shiyiya** [kidjp85/react-id-swiper#480]
I got some mistakes on next .js and I'm not sure whose problem it is .

This is the example I created. 

![image](https://user-images.githubusercontent.com/34017352/102805655-835f2a80-43f6-11eb-9ad5-c709914c0ea4.png)

example:

https://codesandbox.io/s/blissful-sea-2r618?file=/pages/index.js

**Comment by Klypalskyi** [comment]
Is there was any solution for this?

**Comment by shiyiya** [comment]
The above example no longer reports an error.
