### ISSUE TITLE
Question: Controlled swiper

### ISSUE THREAD

**Issue by MildTomato** [kidjp85/react-id-swiper#489]
## Controlling the index of Swiper component

Can the Swiper component be controlled externally, so that an 'active id' could be set?

This is so an external navigation could be used, that could allow the swiper to 'jump' to a specific index.

I would of expected something like this maybe...

```js

const [activeId, setActiveId] = useState(0) 

<Swiper
  activeId={activeId}
  onActiveIndexChange={(slider) => setActiveId(slider.activeIndex)}
...
>
```

**Comment by MildTomato** [comment]
Nevermind, answered my own question.

For anyone else interested, here's how to do it.

```js
function App() {
  // store swiper instance
  const [swiper, setSwiper] = useState(undefined);

  return (
    <>
      {/* Controls outside of Swiper that use swiper instance */}
      <button onClick={() => swiper.slideTo(0)}>Go to 1st slide</button>
      <button onClick={() => swiper.slideTo(1)}>Go to 2nd slide</button>
      {/* Swiper component */}
      <Swiper onSwiper={setSwiper} slidesPerView={1}>
        <SwiperSlide>first slide</SwiperSlide>
        <SwiperSlide>2nd slide</SwiperSlide>
      </Swiper>
    </>
  );
}

```

**Comment by carlosqdev** [comment]
Excellent thanks

**Comment by ogheneovo12** [comment]
this 

> Nevermind, answered my own question.
> 
> For anyone else interested, here's how to do it.
> 
> ```js
> function App() {
>   // store swiper instance
>   const [swiper, setSwiper] = useState(undefined);
> 
>   return (
>     <>
>       {/* Controls outside of Swiper that use swiper instance */}
>       <button onClick={() => swiper.slideTo(0)}>Go to 1st slide</button>
>       <button onClick={() => swiper.slideTo(1)}>Go to 2nd slide</button>
>       {/* Swiper component */}
>       <Swiper onSwiper={setSwiper} slidesPerView={1}>
>         <SwiperSlide>first slide</SwiperSlide>
>         <SwiperSlide>2nd slide</SwiperSlide>
>       </Swiper>
>     </>
>   );
> }
> ```

how do i get the most recent active/real index
