### ISSUE TITLE
How to get the Current Index of the Slider ?

### ISSUE THREAD

**Issue by Darsbir-singh** [kidjp85/react-id-swiper#490]
I have tried thing like slideChange, activeIndex, but not able to get the current index

`let listImageSlickConfig = {
            pagination: {
                el: '.swiper-pagination',
                clickable: true,
            },
            on: {
                slideChange: (index) => {
                    console.log(Swiper.index)
                },
              },
              getSwiper: (i) => console.log(i),
            onSlideChange:function(swipe){
                console.log(swipe.realIndex)
            },
            rebuildOnUpdate:true,
            initialSlide: this.props.initialSlide,
            activeIndex: console.log(Swiper.activeIndex),
            watchOverflow: true,
            ContainerEl: 'section',
            WrapperEl: 'section',
            zoom: true,
        }`

**Comment by LKF92** [comment]
This worked for me : 

`const params = {
    on: {
      slideChange: index => {
        console.log(index.snapIndex);
      },
    },
  }`

**Comment by Darsbir-singh** [comment]
yup, working thanks for help

**Comment by mib00038** [comment]
I would recommend using **realIndexChange** instead of slideChange and **realIndex** instead of snapIndex as additional 'duplicate' slides will be added having their own unique index, in loop mode.

```
  const params = { 
    on: { 
      realIndexChange: (swiper) => console.log(swiper.realIndex) 
    } 
  }
```

**Comment by ShahzaibRiaz** [comment]
where to write this logic could someone please tell?
Either need to attach params on swiperSlide or on container?

**Comment by Nytsee** [comment]
You can simply add it withing your existing options like so :
            .
            .
            .
            spaceBetween: 50,
            slidesPerView: 1,
            loop: true,
 on: {
              slideChange: function() {
                console.log( this.realIndex );
   }


hope this helps !

**Comment by StasSpawn** [comment]
How add on event for html in Angular? 

This is code 

```
<swiper
    #swiperSliderSpinner
    [direction]="'vertical'"
    [pagination]="pagination"
    [mousewheel]="true"
    class="slider-spinner-news-categ">
    <ng-template *ngFor="let item of paginationList" swiperSlide>

    </ng-template>
  </swiper>
```

  


  Is there a way to add [on] ?
