### ISSUE TITLE
No rtl support

### ISSUE THREAD

**Issue by 1mehdifaraji** [kidjp85/react-id-swiper#502]
There is no right to left prop for the swiper component

**Comment by whyboris** [comment]
Until it's available, you can manually set the styles in `css`, for example: https://healthimpactfund.org/ar/

![image](https://user-images.githubusercontent.com/17264277/133002468-74eeed0c-d941-4711-9e14-fa0a5359768a.png)

https://github.com/whyboris/Health-Impact-Fund/blob/master/src/components/layout.js#L27
https://github.com/whyboris/Health-Impact-Fund/blob/master/src/components/arabic.scss#L1

**Comment by whyboris** [comment]
Also, see #474

**Comment by 1mehdifaraji** [comment]
Hi thanks for the comments I figured it out like this :
```
import Swiper from 'react-id-swiper';

<Swiper rtl {...params} ref={swiperRef}>
   .....
</Swiper>
```
