### ISSUE TITLE
es6 require/render

### ISSUE THREAD

**Issue by sergiokopplin** [kidjp85/react-id-swiper#53]
Hello and thanks for the good work here!

---

I was using version 1.3.1 and doing like the files below. I've upgraded to 1.4.0 and now it seems to be broken. Can you help me with this?

I tried several approaches, but i want to know if i am doing something wrong first.

Using last version of React with Isomorphic Rendering.

version: 1.4.0
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `CardSlider`.

---

Container file:
```js
...

let Swiper;

class Container extends Component {
  constructor() {
    super();

    this.swiper = null;
  }

  componentWillMount() {
    Swiper = require('react-id-swiper');
  }

  ...

  render() {
    ...

    return (
      <CardSlider
        params={params}
        slides={this.props.slides}
        Swiper={Swiper}
        updateSliderDimensions={this.updateSliderDimensions}
      />
    );
  }
}

...
```

Presentation file:
```js
...

function CardSlider({ params, slides, Swiper, updateSliderDimensions }) {
  ...

  return (
    <Swiper {...params}>
      {cards}
    </Swiper>
  );
}

...
```

**Comment by kidjp85** [comment]
Hi @sergiokopplin , it should work with `Swiper = require('react-id-swiper').default;`

**Comment by sergiokopplin** [comment]
Thanks!
