### ISSUE TITLE
slidesPerView absolute adjustments?

### ISSUE THREAD

**Issue by Andriy-Kulak** [kidjp85/react-id-swiper#54]
Thank you for all the work that was put into this package!

Is there a way to not define how many slides fit per view, but rather to fit as many slides in the container that react-id-swiper is currently in based on the defined with of each slide?

For example, lets say I have a couple of 200px wide slides.
When container is
- 1,000px --> 5 slides fit in to the swiper,
- 900px --> 4.5 slides fit into the swiper,
- 500px --> 2.5 slides fit into the swiper

... and so on without me having to define the breakpoints. The reason for this, it is hard to define a breakpoints for all screen sizes, etc. and what often ends up happening is the swiper will try to put as an example three 200px slides into a 500px container, there by cutting off some of the slides.

slidesPerView: "auto" --> did not work for me. It simply defaulted to one slide per view.

Thanks!

**Comment by kidjp85** [comment]
Hi @Andriy-Kulak 

You can approach that by using `slidesPerView: "auto" ` and css.

> slidesPerView: "auto" --> did not work for me. It simply defaulted to one slide per view.

Because when you use ` slidesPerView: "auto"`, Swiper won't handle the width of per slide for you anymore, that means if u don't set any specific width for each slide, it's always 100% width.
You can easily set the width of slide by
```css
#auto-slides-per-view {
  .swiper-slide {
    width: 80%;
    &:nth-child(2n) {
      width: 60%;
    }
    &:nth-child(3n) {
      width: 40%;
    }
  }
}
```
More example here:
https://github.com/kidjp85/react-id-swiper-demo/blob/master/app/assets/styles/demo.scss

**Comment by Andriy-Kulak** [comment]
Perfect! Thanks @kidjp85

**Comment by devashissh** [comment]
Hi,

I want swiper slider to work differently on different view port.
For mobile I need it to be horizontal, while in case of Tablet and Desktop I need it to be vertical. Please suggest how we can achieve this?

**Comment by hheinsoee** [comment]
### use `window.innerWidth`
I use like this

`const mySlidesPerView = (window.innerWidth / 300).toFixed(2);`

`const params = {`
`    slidesPerView:mySlidesPerView `
`#}`


`mySlidesPerView` means **the min-width of child element is "300px"**
if u resize window, u need to refresh to get the value of `window.innerWidth` again.
