### ISSUE TITLE
Force update the swiper

### ISSUE THREAD

**Issue by thientran1707** [kidjp85/react-id-swiper#55]
I am having a dynamic array of component to render in swiper, however, when adding the new component to the array, it does not shown correctly in the swiper, which function should I call to force update the swiper

**Comment by kidjp85** [comment]
Hi @thientran1707 , please use params `rebuildOnUpdate : true`  and it should work fine

**Comment by strarsis** [comment]
@kidjp85: Can swiper also just update when new slides were added? Otherwise other components fail to access the contents.

**Comment by mqliutie** [comment]
@kidjp85 Hello I import component using `react-loadable`, These Components will be child of Swiper. If direction: "horizontal" Swiper works well .

But set direction to **vertical** It can not works well 

top and bottom have very large gap. How can I resolve it?
