### ISSUE TITLE
Adding styles (not classes)

### ISSUE THREAD

**Issue by marwej** [kidjp85/react-id-swiper#56]
It would be great if you could add your own styles to the elements. Modifying the class name still don't make it possible to have calculated style properties.

```javascript
const params = {
  containerStyle: {
    padding: 10 + 10,
  },
  spaceBetween: 30
};
return (
  <Swiper {...params}>
    <div>Slide 1</div>
    <div>Slide 2</div>
  </Swiper>
);
```

**Comment by kidjp85** [comment]
Hi @marwej , thanks for your idea. I will consider that. May be in next version we can have more params to manipulate the styles without classname

**Comment by sedubois** [comment]
I would like that too, avoiding CSS files altogether.

**Comment by CodingSam** [comment]
Any progress?

**Comment by SaeedSheikhi** [comment]
Hi @marwej 

it can be solved by using  [glamor](https://github.com/threepointone/glamor), css-in-js  

```javascript

import {css} from 'glamor'

const padding : 10+10;
const params = {
  containerClass: `swiper-container ${css({ padding })}`,
  spaceBetween: 30
};
return (
  <Swiper {...params}>
    <div>Slide 1</div>
    <div>Slide 2</div>
  </Swiper>
);

```
