### ISSUE TITLE
Example with manipulating swiper from outside swiper component

### ISSUE THREAD

**Issue by kalimullahansari** [kidjp85/react-id-swiper#57]
hey,

  How can i hide next button on reaching last slide? Similarly how to hide prev button when first slide is present in swiper container?. if i am manipulating  swiper from outside.

**Comment by kidjp85** [comment]
Hi @kalimullahansari, for the case manipulating swiper from outside, you can refer from the example in doc. Once you have `this.swiper`, you can easily detect last or first slide by `this.swiper. isBeginning ` or `this.swiper. isEnd ` and add class name or styles to hide it
