### ISSUE TITLE
How to use API methods on Swiper React element?

### ISSUE THREAD

**Issue by ruaanvds** [kidjp85/react-id-swiper#62]
Hi kidjp85, 

I'm fairly certain I'm missing something obvious, but how would I go about using the [Swiper API ](http://idangero.us/swiper/api/)methods on my React element?

I need to use the **slideTo** method in particular:

`mySwiper.slideTo(index, speed, runCallbacks);`

Thanks!

**Comment by kidjp85** [comment]
Hi @ruaanvds 

Please check README again for https://github.com/kidjp85/react-id-swiper#example-with-manipulating-swiper-from-outside-swiper-component

**Comment by ruaanvds** [comment]
Apologies, @kidjp85 - somehow missed that part. 

Thanks for a great library!
