### ISSUE TITLE
All slides rendering on first slide?

### ISSUE THREAD

**Issue by krustina** [kidjp85/react-id-swiper#63]
Hi again

So, ive been having this issue for a while now. When i want to use a horizontal swiper (and i copy the code exactly as the demo) i get all my slide contents rendering on the FIRST slide only...and the swiper still swipes in the correct direction (only without any info on the slide, of course).

Any thoughts at all? I really need to figure this out soon. 

```
class BedOfRoses extends React.Component {
    render() {
        const params = {
            pagination: '.swiper-pagination',
            paginationClickable: true,
            nextButton: '.swiper-button-next',
            prevButton: '.swiper-button-prev',
            spaceBetween: 30
        };
        return (
            <Swiper>
                <div>Slide 1</div>
                <div>Slide 2</div>
                <div>Slide 3</div>
                <div>Slide 4</div>
                <div>Slide 5</div>
            </Swiper>

        );

    }
}

export default BedOfRoses;
```

![untitled](https://user-images.githubusercontent.com/21249168/29008511-e6322652-7add-11e7-80ef-5d2c7d02ad1f.gif)

**Comment by TomOne** [comment]
Have you included the `swiper.css` file?

**Comment by thomaslein** [comment]
I have the same issue and I include the swiper.scss file.
