### ISSUE TITLE
Swiper shows a black line border below its component

### ISSUE THREAD

**Issue by iamsaksham** [kidjp85/react-id-swiper#65]
The swiper has a black solid line border at the bottom of the component. It looks kind of weird when I use it on white background, then an unnecessary black line runs below this component

<img width="1437" alt="screen shot 2017-09-09 at 2 28 37 pm" src="https://user-images.githubusercontent.com/13564312/30238766-42a44d14-956b-11e7-8fc0-0f7abd5817f3.png">

**Comment by kidjp85** [comment]
Hi @iamsaksham , can you check your styles one more time ? Cause I can't reproduce it with white background

**Comment by iamsaksham** [comment]
@kidjp85 I'll try to replicate it in some jsbin or fiddle. Closing till then
