### ISSUE TITLE
Swiper does not work with images properly

### ISSUE THREAD

**Issue by oliverwatkins** [kidjp85/react-id-swiper#66]
I am upgrading my website from using idangerous swiper to using this react wrapper for the swiper.

It does not work with images as far as I can tell :

My code looks like this :

```
import c1 from "./ichartsImages/grid4_yfill.png"
import c2 from "./ichartsImages/grid1.png"
        
...

<Swiper>
  <div style={{backgroundImage:"url(" + c2 + ")"}}></div>
  <div style={{backgroundImage:"url(" + c3 + ")"}}></div>
</Swiper>
```
The images to do not fit properly, and are repeated. I would expect the component to fit the images for me.

In my old code, there were a bunch of CSS classes which are missing in this component. However this worked perfectly :  

```
    <div class="swiper-container">
        <div class="swiper-wrapper">
            <div class="swiper-slide" style="background-image:url(ichartsImages/grid4_yfill.png)"></div>
            <div class="swiper-slide" style="background-image:url(ichartsImages/grid1.png)"></div>
```

Not sure why the react component does not work. Perhaps you need CSS classes? Anyway, i think the examples need to be more comprehensive.

**Comment by kidjp85** [comment]
Hi @oliverwatkins , did you set fixed width for each slide ?
