### ISSUE TITLE
Update to React 16

### ISSUE THREAD

**Issue by glintik** [kidjp85/react-id-swiper#68]
Hi,

React 16 has been released recently, so it's a good reason to update package.json.
I tested my app with the current react-id-swiper and React 16, works good.

**Comment by kidjp85** [comment]
1.5.0-beta is on going :) . I am so busy recently, try to release new version with React Fiber soon

**Comment by glintik** [comment]
Hi @kidjp85,

I tried to run on React 16, works without issues, so version upgrade can be done without any hassles.

**Comment by akichim21** [comment]
https://github.com/kidjp85/react-id-swiper/pull/70

**Comment by kidjp85** [comment]
Available in 1.5.0
