### ISSUE TITLE
Heads up; not compatible with server side rendered React applications

### ISSUE THREAD

**Issue by petertenhoor** [kidjp85/react-id-swiper#69]
Hi there, I tested this package in my React application which is rendered by my node server before the client takes over.

Because the window variable and multiple DOM references are used in the swiper library, I can't use it. My Node server can't access these client only references.

Example: `var ua = window.navigator.userAgent.toLowerCase();`

Consider this as a heads up. I bet more people are running into this issue. Fixing this would mean that you have to port the entire swiper library to React conventions, which is a lot of work.

**Comment by fabiolimarocha** [comment]
I've been through the same problem..

**Comment by kidjp85** [comment]
Hi @petertenhoor , we already discussed lots of time about this issue. For now, Swiper itself doesn't support server rendering. For temporary solution u can find from here https://github.com/kidjp85/react-id-swiper/issues/48

They already have PR for server rendering , but it's not being merged yet. Hope we can have it on next version of Swiper
https://github.com/nolimits4web/Swiper/pull/2123
