### ISSUE TITLE
Linking two swipers together

### ISSUE THREAD

**Issue by timkindberg** [kidjp85/react-id-swiper#75]
Is it possible to achieve linking of two swipers like this vanilla swiper demo is doing?: http://idangero.us/swiper/demos/300-thumbs-gallery.html

The vanilla swiper source code is here: https://github.com/nolimits4web/Swiper/blob/master/demos/300-thumbs-gallery.html

They are doing something like this (I believe the bottom two lines are the important linking bits):
```js
    var galleryTop = new Swiper('.gallery-top', {
      spaceBetween: 10,
      navigation: {
        nextEl: '.swiper-button-next',
        prevEl: '.swiper-button-prev',
      },
    });
    var galleryThumbs = new Swiper('.gallery-thumbs', {
      spaceBetween: 10,
      centeredSlides: true,
      slidesPerView: 'auto',
      touchRatio: 0.2,
      slideToClickedSlide: true,
    });
    galleryTop.controller.control = galleryThumbs;
    galleryThumbs.controller.control = galleryTop;
```

If this is not possible I'd like to suggest as a feature request.

**Comment by kidjp85** [comment]
I didn't try it yet. But I think it's possible to do it. I will try to add this to demo page.

**Comment by KubaKrychowski** [comment]
> I didn't try it yet. But I think it's possible to do it. I will try to add this to demo page.

Hey, have You solved it already? I cant find any good way to do this.
