### ISSUE TITLE
Make v1.5.0 compatible with React 15

### ISSUE THREAD

**Issue by gareys** [kidjp85/react-id-swiper#76]
I can't see any reason in particular to prevent someone from using v1.5.0 on react ^15.0.0.

Let's add support back.

**Comment by gareys** [comment]
Opened PR #77 to address this issue. Please review and test prior to publishing. I haven't had time to test yet, but it looks good.

**Comment by kidjp85** [comment]
Hi @gareys , I'm thinking of removing the peerDependencies in next release. Thank you for your PR anyway 👍

**Comment by gareys** [comment]
Is there anything I can do to move that forward? I'm interested in making the 1.5.x version compatible with my project ASAP. In the meantime I'm going to fork.

**Comment by kidjp85** [comment]
Hi @gareys , I will release new version within today. So don't worry :)
