### ISSUE TITLE
Event Props do not work/reflect actual swiper API

### ISSUE THREAD

**Issue by gareys** [kidjp85/react-id-swiper#80]
The Swiper api utilizes an object `on` to house the event listeners in the params setup of the swiper. The api of this react utility is not compatible and can be misleading. The propTypes and examples should be updated.

**Comment by kidjp85** [comment]
Hi @gareys , can u give more detail info ? The demo is outdated and only for 1.3.0 version.

**Comment by gareys** [comment]
I'll open a PR.

**Comment by gareys** [comment]
#81

**Comment by kidjp85** [comment]
Thanks for your PR. It will be fixed with Ver 1.5.2

**Comment by gareys** [comment]
You're welcome. It may be prudent to review all of the swiper api params and make sure the prop-types in this lib are up to date.
