### ISSUE TITLE
init event no long passes swiper instance as an argument

### ISSUE THREAD

**Issue by gareys** [kidjp85/react-id-swiper#84]
this doesn't work anymore:
```
render() {
  const params = {
    pagination: {
      el: '.swiper-pagination',
      type: 'bullets',
      clickable: true
    },
    navigation: {
      nextEl: '.swiper-button-next',
      prevEl: '.swiper-button-prev'
    },
    onInit: (swiper) => {
      this.swiper = swiper
    }
  }

  return(
    <div>
      <Swiper {...params}>
        <div>Slide 1</div>
        <div>Slide 2</div>
        <div>Slide 3</div>
        <div>Slide 4</div>
        <div>Slide 5</div>
      </Swiper>
    </div>
  )
}
```
even this won't work as the swiper instance is no longer passed as an argument to the init event:
```
on: {
  init: (swiper) => {
    this.swiper = swiper
  }
}
```

but... this works:
```
render() {
  const params = {
    navigation: {
      nextEl: '.swiper-button-next',
      prevEl: '.swiper-button-prev'
    },
    pagination: {
      el: '.swiper-pagination',
      dynamicBullets: true,
      clickable: true
    }
  };

  return(
    <div>
      <Swiper {...params} ref={node => this.swiper = node !== null ? node.swiper : null }>
        <div>Slide 1</div>
        <div>Slide 2</div>
        <div>Slide 3</div>
        <div>Slide 4</div>
        <div>Slide 5</div>
      </Swiper>
    </div>
  );
}
```

**Comment by gareys** [comment]
We should update the docs to reflect this... or discuss a more eloquent way of setting the swiper instance. This was just my method.

**Comment by kidjp85** [comment]
Hi @gareys , I agree that we should provide new way to get swiper instance.

**Comment by gareys** [comment]
this can be closed unless you think further work could be done. I personally suggested `ref={node => this.swiper = node !== null ? node.swiper : null }` and saw that you used `{node => if(node) this.swiper = node.swiper }`.  Any opinion on which is more fool proof?

I don't really see a scenario where `node === null`, but in the case the there is, my example would set `this.swiper = null;`, whereas your example would continue to refer to an old instance of swiper. Again, I don't know when this would ever happen, but I just built my code to withstand that potential fault.
