### ISSUE TITLE
1.5.3 is broke

### ISSUE THREAD

**Issue by maxefi** [kidjp85/react-id-swiper#87]
![screen shot 2017-10-31 at 17 20 31](https://user-images.githubusercontent.com/14819868/32230309-e8524a88-be63-11e7-8f98-579279841e92.png)

hello there. I think you newest version is not working, slides are not being rendered correctly and slider cannot be closed.

**Comment by kidjp85** [comment]
Hi @maxefi , can u share ur component code ?

**Comment by kidjp85** [comment]
Since no more confirmation. I closed this issue
