### ISSUE TITLE
Parallax support

### ISSUE THREAD

**Issue by bramdoppen** [kidjp85/react-id-swiper#92]
Hi! I can't seem to get the parallax background working without changing your index.js file.

According to [this](https://github.com/nolimits4web/Swiper/blob/master/demos/360-parallax.html) the parallax background needs to be inserted between the "swiper-container" and the "swiper-wrapper". There is no option for that right now (as far as I can see).

Perhaps you can consider supporting parallax in this plugin?

Thanks in advance!

**Comment by gareys** [comment]
Could you open a PR with your changes to the index.js? I'm interested to see.

**Comment by kidjp85** [comment]
I'm updating demo page now. I will try to add parallax demo and see if we need to change core file or not.

**Comment by kidjp85** [comment]
Can use parallax with v1.5.5. Check demo page for more detail
